package com.applovin.impl.sdk.c;

import android.net.Uri;
import com.applovin.impl.adview.AppLovinTouchToClickListener;
import com.applovin.impl.b.n;
import com.applovin.impl.sdk.nativeAd.AppLovinNativeAdImpl;
import com.applovin.impl.sdk.utils.AppLovinSdkExtraParameterKey;
import com.applovin.impl.sdk.utils.p;
import com.applovin.mediation.MaxAdFormat;
import com.applovin.sdk.AppLovinAdSize;
import com.lenovo.anyshare.InterfaceC13225hhc;
import com.lenovo.anyshare.UFc;
import com.unity3d.services.banners.UnityBannerSize;
import com.vungle.warren.log.LogSender;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

/* loaded from: classes2.dex */
public class b<T> implements Comparable {
    public final T aKf;
    public final String name;
    public static final List<?> aKd = Arrays.asList(Boolean.class, Float.class, Integer.class, Long.class, String.class);
    public static final Map<String, b<?>> aKe = new HashMap(512);
    public static final b<Boolean> aKg = d("is_disabled", false);
    public static final b<String> aKh = d(LogSender.PREFS_DEVICE_ID_KEY, "");
    public static final b<Boolean> aKi = d("rss", true);
    public static final b<Boolean> aKj = d("rssoitf", false);
    public static final b<String> aKk = d("device_token", "");
    public static final b<Long> aKl = d("publisher_id", 0L);
    public static final b<Boolean> aKm = d("is_verbose_logging", false);
    public static final b<String> aKn = d(com.anythink.expressad.e.a.b.bI, "");
    public static final b<String> aKo = d("sc2", "");
    public static final b<String> aKp = d("sc3", "");
    public static final b<String> aKq = d("server_installed_at", "");
    public static final b<Boolean> aKr = d("pnrc", false);
    public static final b<Boolean> aKs = d("clear_completion_callback_on_failure", false);
    public static final b<Long> aKt = d("sicd_ms", 0L);
    public static final b<Integer> aKu = d("logcat_max_line_size", 1000);
    public static final b<Integer> aKv = d("stps", 2);
    public static final b<Boolean> aKw = d("exception_handler_enabled", true);
    public static final b<Integer> aKx = d("network_thread_count", 2);
    public static final b<Integer> aKy = d("aei", -1);
    public static final b<Integer> aKz = d("mei", -1);
    public static final b<Boolean> aKA = d("bdae", false);
    public static final b<Boolean> aKB = d("tewllm", true);
    public static final b<Boolean> aKC = d("lisvib", false);
    public static final b<Boolean> aKD = d("tewplosda", true);
    public static final b<Boolean> aKE = d("srwbe", false);
    public static final b<Integer> aKF = d("malaera", -1);
    public static final b<String> aKG = d("eralaf", "");
    public static final b<String> aKH = d("ps_atu", "");
    public static final b<Boolean> aKI = d("ah_cvc", true);
    public static final b<Boolean> aKJ = d("ah_cdde", true);
    public static final b<Boolean> aKK = d("ah_crut", true);
    public static final b<Boolean> aKL = d("init_omsdk", true);
    public static final b<String> aKM = d("omsdk_partner_name", AppLovinNativeAdImpl.AD_RESPONSE_TYPE_APPLOVIN);
    public static final b<Boolean> aKN = d("publisher_can_show_consent_dialog", true);
    public static final b<String> aKO = d("consent_dialog_url", "https://assets.applovin.com/gdpr/flow_v1/gdpr-flow-1.html");
    public static final b<Boolean> aKP = d("consent_dialog_immersive_mode_on", false);
    public static final b<Long> aKQ = d("consent_dialog_show_from_alert_delay_ms", 450L);
    public static final b<Boolean> aKR = d("alert_consent_for_dialog_rejected", false);
    public static final b<Boolean> aKS = d("alert_consent_for_dialog_closed", false);
    public static final b<Boolean> aKT = d("alert_consent_for_dialog_closed_with_back_button", false);
    public static final b<Boolean> aKU = d("alert_consent_after_init", false);
    public static final b<Long> aKV = d("alert_consent_after_init_interval_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(5)));
    public static final b<Long> aKW = d("alert_consent_after_dialog_rejection_interval_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(30)));
    public static final b<Long> aKX = d("alert_consent_after_dialog_close_interval_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(5)));
    public static final b<Long> aKY = d("alert_consent_after_dialog_close_with_back_button_interval_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(5)));
    public static final b<Long> aKZ = d("alert_consent_after_cancel_interval_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(10)));
    public static final b<Long> aLa = d("alert_consent_reschedule_interval_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(5)));
    public static final b<String> aLb = d("text_alert_consent_title", "Make this App Better and Stay Free!");
    public static final b<String> aLc = d("text_alert_consent_body", "If you don't give us consent to use your data, you will be making our ability to support this app harder, which may negatively affect the user experience.");
    public static final b<String> aLd = d("text_alert_consent_yes_option", "I Agree");
    public static final b<String> aLe = d("text_alert_consent_no_option", UFc.b);
    public static final b<Long> aLf = d("ttc_max_click_duration_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(1)));
    public static final b<Integer> aLg = d("ttc_max_click_distance_dp", 10);
    public static final b<Integer> aLh = d("ttc_acrsv2a", Integer.valueOf(AppLovinTouchToClickListener.ClickRecognitionState.ACTION_DOWN.ordinal()));
    public static final b<Integer> aLi = d("ttc_acrsnv", Integer.valueOf(AppLovinTouchToClickListener.ClickRecognitionState.ACTION_DOWN.ordinal()));
    public static final b<Integer> aLj = d("ttc_acrsa", Integer.valueOf(AppLovinTouchToClickListener.ClickRecognitionState.ACTION_DOWN.ordinal()));
    public static final b<Integer> aLk = d("ttc_acrsn", Integer.valueOf(AppLovinTouchToClickListener.ClickRecognitionState.ACTION_DOWN.ordinal()));
    public static final b<Integer> aLl = d("ttc_edge_buffer_dp", 0);
    public static final b<String> aLm = d("whitelisted_postback_endpoints", "https://prod-a.applovin.com,https://rt.applovin.com/4.0/pix, https://rt.applvn.com/4.0/pix,https://ms.applovin.com/,https://ms.applvn.com/");
    public static final b<String> aLn = d("fetch_settings_endpoint", "https://ms.applovin.com/");
    public static final b<String> aLo = d("fetch_settings_backup_endpoint", "https://ms.applvn.com/");
    public static final b<String> aLp = d("adserver_endpoint", "https://a.applovin.com/");
    public static final b<String> aLq = d("adserver_backup_endpoint", "https://a.applvn.com/");
    public static final b<String> aLr = d("api_endpoint", "https://d.applovin.com/");
    public static final b<String> aLs = d("api_backup_endpoint", "https://d.applvn.com/");
    public static final b<String> aLt = d("event_tracking_endpoint_v2", "https://rt.applovin.com/");
    public static final b<String> aLu = d("event_tracking_backup_endpoint_v2", "https://rt.applvn.com/");
    public static final b<String> aLv = d("token_type_prefixes_r", "4!");
    public static final b<String> aLw = d("token_type_prefixes_arj", "json_v3!");
    public static final b<String> aLx = d("top_level_events", "landing,paused,resumed,cf_start,tos_ok,gdpr_ok,ref,rdf,checkout,iap");
    public static final b<String> aLy = d("valid_super_property_types", String.class.getName() + "," + Integer.class.getName() + "," + Long.class.getName() + "," + Double.class.getName() + "," + Float.class.getName() + "," + Date.class.getName() + "," + Uri.class.getName() + "," + List.class.getName() + "," + Map.class.getName());
    public static final b<Boolean> aLz = d("persist_super_properties", true);
    public static final b<Integer> aLA = d("super_property_string_max_length", 1024);
    public static final b<Integer> aLB = d("super_property_url_max_length", 1024);
    public static final b<Boolean> aLC = d("use_per_format_cache_queues", true);
    public static final b<Boolean> aLD = d("cache_cleanup_enabled", false);
    public static final b<Long> aLE = d("cache_file_ttl_seconds", Long.valueOf(TimeUnit.DAYS.toSeconds(1)));
    public static final b<Integer> aLF = d("cache_max_size_mb", -1);
    public static final b<String> aLG = d("precache_delimiters", ")]', ");
    public static final b<Boolean> aLH = d("ad_resource_caching_enabled", true);
    public static final b<String> aLI = d("resource_cache_prefix", "https://vid.applovin.com/,https://stage-vid.applovin.com/,https://pdn.applovin.com/,https://stage-pdn.applovin.com/,https://img.applovin.com/,https://stage-img.applovin.com/,https://d.applovin.com/,https://assets.applovin.com/,https://stage-assets.applovin.com/,https://cdnjs.cloudflare.com/,http://vid.applovin.com/,http://stage-vid.applovin.com/,http://pdn.applovin.com/,http://stage-pdn.applovin.com/,http://img.applovin.com/,http://stage-img.applovin.com/,http://d.applovin.com/,http://assets.applovin.com/,http://stage-assets.applovin.com/,http://cdnjs.cloudflare.com/,http://u.appl.vn/,https://u.appl.vn/,https://res.applovin.com/,https://res1.applovin.com/,https://res2.applovin.com/,https://res3.applovin.com/,http://res.applovin.com/,http://res1.applovin.com/,http://res2.applovin.com/,http://res3.applovin.com/");
    public static final b<String> aLJ = d("preserved_cached_assets", "sound_off.png,sound_on.png,closeOptOut.png,1381250003_28x28.png,zepto-1.1.3.min.js,jquery-2.1.1.min.js,jquery-1.9.1.min.js,jquery.knob.js");
    public static final b<Integer> aLK = d("resource_max_filename_length", 255);
    public static final b<Boolean> aLL = d("ccrc", false);
    public static final b<Integer> aLM = d("mcct", 3);
    public static final b<Integer> aLN = d("mchct", 3);
    public static final b<Boolean> aLO = d("dficf", false);
    public static final b<Boolean> aLP = d("decr", false);
    public static final b<Boolean> aLQ = d("dcrome", false);
    public static final b<Boolean> aLR = d("dcrobs", false);
    public static final b<Boolean> aLS = d("upcan", false);
    public static final b<Boolean> aLT = d("ugfnfhr", false);
    public static final b<Boolean> aLU = d("lfeufc", false);
    public static final b<Boolean> aLV = d("pcro", false);
    public static final b<Boolean> aLW = d("efecobt", false);
    public static final b<Boolean> aLX = d("saewib", false);
    public static final b<Long> aLY = d("fsae_ms", -1L);
    public static final b<Boolean> aLZ = d("raae", false);
    public static final b<Integer> aMa = d("vr_retry_count_v1", 1);
    public static final b<Integer> aMb = d("cr_retry_count_v1", 1);
    public static final b<String> aMc = d("text_incent_warning_title", "Attention!");
    public static final b<String> aMd = d("text_incent_warning_body", "You won’t get your reward if the video hasn’t finished.");
    public static final b<String> aMe = d("text_incent_warning_close_option", "Close");
    public static final b<String> aMf = d("text_incent_warning_continue_option", "Keep Watching");
    public static final b<String> aMg = d("text_incent_nonvideo_warning_title", "Attention!");
    public static final b<String> aMh = d("text_incent_nonvideo_warning_body", "You won’t get your reward if the game hasn’t finished.");
    public static final b<String> aMi = d("text_incent_nonvideo_warning_close_option", "Close");
    public static final b<String> aMj = d("text_incent_nonvideo_warning_continue_option", "Keep Playing");
    public static final b<Integer> aMk = d("close_button_touch_area", 0);
    public static final b<Integer> aMl = d("close_button_outside_touch_area", 0);
    public static final b<Boolean> aMm = d("creative_debugger_enabled", true);
    public static final b<Long> aMn = d("viewability_adview_imp_delay_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(1)));
    public static final b<Integer> aMo = d("viewability_adview_banner_min_width", 320);
    public static final b<Integer> aMp = d("viewability_adview_banner_min_height", Integer.valueOf(AppLovinAdSize.BANNER.getHeight()));
    public static final b<Integer> aMq = d("viewability_adview_mrec_min_width", Integer.valueOf(MaxAdFormat.MREC.getSize().getWidth()));
    public static final b<Integer> aMr = d("viewability_adview_mrec_min_height", Integer.valueOf(MaxAdFormat.MREC.getSize().getHeight()));
    public static final b<Integer> aMs = d("viewability_adview_leader_min_width", Integer.valueOf((int) UnityBannerSize.BannerSize.LEADERBOARD_WIDTH));
    public static final b<Integer> aMt = d("viewability_adview_leader_min_height", Integer.valueOf(AppLovinAdSize.LEADER.getHeight()));
    public static final b<Integer> aMu = d("viewability_adview_native_min_width", 0);
    public static final b<Integer> aMv = d("viewability_adview_native_min_height", 0);
    public static final b<Float> aMw = d("viewability_adview_min_alpha", Float.valueOf(10.0f));
    public static final b<Long> aMx = d("viewability_timer_min_visible_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(1)));
    public static final b<Long> aMy = d("viewability_timer_interval_ms", 100L);
    public static final b<Integer> aMz = d("expandable_close_button_size", 27);
    public static final b<Integer> aMA = d("expandable_h_close_button_margin", 10);
    public static final b<Integer> aMB = d("expandable_t_close_button_margin", 10);
    public static final b<Boolean> aMC = d("expandable_lhs_close_button", false);
    public static final b<Integer> aMD = d("expandable_close_button_touch_area", 0);
    public static final b<Boolean> aME = d("iaad", false);
    public static final b<String> aMF = d("js_tag_schemes", "applovin,mopub");
    public static final b<String> aMG = d("js_tag_load_success_hosts", "load,load_succeeded");
    public static final b<String> aMH = d("js_tag_load_failure_hosts", "failLoad,load_failed");
    public static final b<Integer> aMI = d("auxiliary_operations_threads", 1);
    public static final b<Long> aMJ = d("fullscreen_ad_pending_display_state_timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(10)));
    public static final b<Long> aMK = d("fullscreen_ad_showing_state_timeout_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(2)));
    public static final b<Boolean> aML = d("lhs_close_button_video", false);
    public static final b<Integer> aMM = d("close_button_right_margin_video", 4);
    public static final b<Integer> aMN = d("close_button_size_video", 30);
    public static final b<Integer> aMO = d("close_button_top_margin_video", 8);
    public static final b<Integer> aMP = d("video_countdown_clock_margin", 10);
    public static final b<Integer> aMQ = d("video_countdown_clock_gravity", 83);
    public static final b<Integer> aMR = d("countdown_clock_size", 32);
    public static final b<Integer> aMS = d("countdown_clock_stroke_size", 4);
    public static final b<Integer> aMT = d("countdown_clock_text_size", 28);
    public static final b<Boolean> aMU = d("draw_countdown_clock", true);
    public static final b<Long> aMV = d("inter_display_delay", 200L);
    public static final b<Long> aMW = d("maximum_close_button_delay_seconds", 999L);
    public static final b<Boolean> aMX = d("respect_close_button", true);
    public static final b<Boolean> aMY = d("lhs_skip_button", true);
    public static final b<Boolean> aMZ = d("mute_controls_enabled", false);
    public static final b<Boolean> aNa = d("allow_user_muting", true);
    public static final b<Boolean> aNb = d("mute_videos", false);
    public static final b<Boolean> aNc = d("show_mute_by_default", false);
    public static final b<Boolean> aNd = d("mute_with_user_settings", true);
    public static final b<Integer> aNe = d("mute_button_size", 32);
    public static final b<Integer> aNf = d("mute_button_margin", 10);
    public static final b<Integer> aNg = d("mute_button_gravity", 85);
    public static final b<Long> aNh = d("progress_bar_step", 25L);
    public static final b<Integer> aNi = d("progress_bar_scale", 10000);
    public static final b<Integer> aNj = d("progress_bar_vertical_padding", -8);
    public static final b<Integer> aNk = d("vs_buffer_indicator_size", 50);
    public static final b<Boolean> aNl = d("video_zero_length_as_computed", false);
    public static final b<Long> aNm = d("set_poststitial_muted_initial_delay_ms", 500L);
    public static final b<Boolean> aNn = d("fasuic", true);
    public static final b<Boolean> aNo = d("fsahrpg", true);
    public static final b<Boolean> aNp = d("eaafrwsoa", true);
    public static final b<Long> aNq = d("postitial_progress_bar_step_ms", 25L);
    public static final b<Boolean> aNr = d("postitial_progress_bar_on_bottom", true);
    public static final b<Integer> aNs = d("postitial_progress_bar_vertical_padding", -8);
    public static final b<Integer> aNt = d("postitial_progress_bar_scale", 10000);
    public static final b<Boolean> aNu = d("sutfaa", true);
    public static final b<Boolean> aNv = d("fahosu", false);
    public static final b<Boolean> aNw = d("nsuttcl", false);
    public static final b<Integer> aNx = d("submit_postback_timeout", Integer.valueOf((int) TimeUnit.SECONDS.toMillis(10)));
    public static final b<Integer> aNy = d("submit_postback_retries", 4);
    public static final b<Integer> aNz = d("max_postback_attempts", 3);
    public static final b<Integer> aNA = d("max_persisted_postbacks", 100);
    public static final b<Integer> aNB = d("submit_web_tracker_timeout", Integer.valueOf((int) TimeUnit.SECONDS.toMillis(7)));
    public static final b<Boolean> aNC = d("sossp", false);
    public static final b<Boolean> aND = d("spp", true);
    public static final b<Boolean> aNE = d("retry_on_all_errors", false);
    public static final b<Integer> aNF = d("get_retry_delay_v1", Integer.valueOf((int) TimeUnit.SECONDS.toMillis(10)));
    public static final b<Integer> aNG = d("http_connection_timeout", Integer.valueOf((int) TimeUnit.SECONDS.toMillis(30)));
    public static final b<Integer> aNH = d("http_socket_timeout", Integer.valueOf((int) TimeUnit.SECONDS.toMillis(20)));
    public static final b<Boolean> aNI = d("force_ssl", false);
    public static final b<Integer> aNJ = d("fetch_ad_connection_timeout", Integer.valueOf((int) TimeUnit.SECONDS.toMillis(30)));
    public static final b<Integer> aNK = d("fetch_ad_retry_count_v1", 1);
    public static final b<Boolean> aNL = d("faer", false);
    public static final b<Boolean> aNM = d("faroae", false);
    public static final b<Integer> aNN = d("submit_data_retry_count_v1", 1);
    public static final b<Integer> aNO = d("response_buffer_size", 16000);
    public static final b<Integer> aNP = d("fetch_basic_settings_connection_timeout_ms", Integer.valueOf((int) TimeUnit.SECONDS.toMillis(10)));
    public static final b<Integer> aNQ = d("fetch_basic_settings_retry_count", 3);
    public static final b<Boolean> aNR = d("fetch_basic_settings_on_reconnect", false);
    public static final b<Boolean> aNS = d("skip_fetch_basic_settings_if_not_connected", false);
    public static final b<Integer> aNT = d("fetch_basic_settings_retry_delay_ms", Integer.valueOf((int) TimeUnit.SECONDS.toMillis(2)));
    public static final b<Boolean> aNU = d("idflrwbe", false);
    public static final b<Boolean> aNV = d("falawpr", false);
    public static final b<Boolean> aNW = d("sort_query_parameters", false);
    public static final b<Long> aNX = d("communicator_request_timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(10)));
    public static final b<Integer> aNY = d("communicator_request_retry_count", 3);
    public static final b<Long> aNZ = d("communicator_request_retry_delay_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(2)));
    public static final b<Long> aOa = d("rfbsd_ms", -1L);
    public static final b<Long> aOb = d("ehkpd_ms", 500L);
    public static final b<Boolean> aOc = d("rironc", false);
    public static final b<Boolean> aOd = d("rroncbd", false);
    public static final b<Long> aOe = d("wverc_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(5)));
    public static final b<Integer> aOf = d("ad_session_minutes", 60);
    public static final b<Boolean> aOg = d("session_tracking_cooldown_on_event_fire", true);
    public static final b<Long> aOh = d("session_tracking_resumed_cooldown_minutes", 90L);
    public static final b<Long> aOi = d("session_tracking_paused_cooldown_minutes", 90L);
    public static final b<Boolean> aOj = d("dc_v2", false);
    public static final b<Boolean> aOk = d("dce", true);
    public static final b<Boolean> aOl = d("qq", false);
    public static final b<Boolean> aOm = d("qq1", true);
    public static final b<Boolean> aOn = d("qq2", true);
    public static final b<Boolean> aOo = d("qq3", true);
    public static final b<Boolean> aOp = d("qq4", true);
    public static final b<Boolean> aOq = d("qq5", true);
    public static final b<Boolean> aOr = d("qq6", true);
    public static final b<Boolean> aOs = d("qq7", true);
    public static final b<Boolean> aOt = d("qq8", true);
    public static final b<Boolean> aOu = d("qq9", false);
    public static final b<Boolean> aOv = d("qq10", true);
    public static final b<Boolean> aOw = d("qq11", true);
    public static final b<Boolean> aOx = d("pui", true);
    public static final b<String> aOy = d("plugin_version", "");
    public static final b<Boolean> aOz = d("hgn", true);
    public static final b<Boolean> aOA = d("cso", true);
    public static final b<Boolean> aOB = d("cfs", true);
    public static final b<Boolean> aOC = d("cmi", true);
    public static final b<Boolean> aOD = d("crat", true);
    public static final b<Boolean> aOE = d("cvs", true);
    public static final b<Boolean> aOF = d("caf", true);
    public static final b<Boolean> aOG = d("cf", true);
    public static final b<Boolean> aOH = d("cmtl", true);
    public static final b<Boolean> aOI = d("cnr", true);
    public static final b<Boolean> aOJ = d("ccr", false);
    public static final b<Boolean> aOK = d("adr", true);
    public static final b<Float> aOL = d("volume_normalization_factor", Float.valueOf(6.6666665f));
    public static final b<Boolean> aOM = d("system_user_agent_collection_enabled", false);
    public static final b<Boolean> aON = d(AppLovinSdkExtraParameterKey.USER_AGENT_COLLECTION_ENABLED, false);
    public static final b<Boolean> aOO = d("collect_device_angle", true);
    public static final b<Boolean> aOP = d("collect_device_movement", true);
    public static final b<Boolean> aOQ = d("cipc", true);
    public static final b<Float> aOR = d("movement_degradation", Float.valueOf(0.75f));
    public static final b<Integer> aOS = d("device_sensor_period_ms", 250);
    public static final b<Boolean> aOT = d("idcw", false);
    public static final b<Integer> aOU = d("fetch_basic_settings_delay_ms", 1500);
    public static final b<String> aOV = d("mps", "");
    public static final b<Integer> aOW = d("mpsl", 3);
    public static final b<String> aOX = d("mpis", "com.applovin,dalvik,java,android,com.android");
    public static final b<Boolean> aOY = d("cmps", false);
    public static final b<Integer> aOZ = d("dcttl_1_seconds", 5);
    public static final b<Integer> aPa = d("dcttl_2_seconds", 30);
    public static final b<Integer> aPb = d("dcttl_3_seconds", Integer.valueOf((int) TimeUnit.MINUTES.toSeconds(1)));
    public static final b<Integer> aPc = d("dcttl_4_seconds", Integer.valueOf((int) TimeUnit.MINUTES.toSeconds(30)));
    public static final b<Integer> aPd = d("dcttl_5_seconds", Integer.valueOf((int) TimeUnit.HOURS.toSeconds(1)));
    public static final b<Integer> aPe = d("dcttl_6_seconds", Integer.valueOf((int) TimeUnit.DAYS.toSeconds(1)));
    public static final b<Boolean> aPf = d("cclia", true);
    public static final b<Long> aPg = d("lccdm", 10L);
    public static final b<Integer> aPh = d("lmfd", 2);
    public static final b<Boolean> aPi = d("is_track_ad_info", true);
    public static final b<Integer> aPj = d("submit_ad_stats_max_count", 500);
    public static final b<String> aPk = d("vast_image_html", "<html><head><style>html,body{height:100%;width:100%}body{background-image:url({SOURCE});background-repeat:no-repeat;background-size:contain;background-position:center;}a{position:absolute;top:0;bottom:0;left:0;right:0}</style></head><body><a href=\"applovin://com.applovin.sdk/adservice/track_click_now\"></a></body></html>");
    public static final b<String> aPl = d("vast_link_html", "<html><head><style>html,body,iframe{height:100%;width:100%;}body{margin:0}iframe{border:0;overflow:hidden;position:absolute}</style></head><body><iframe src={SOURCE} frameborder=0></iframe></body></html>");
    public static final b<Integer> aPm = d("vast_max_response_length", 640000);
    public static final b<Integer> aPn = d("vast_max_wrapper_depth", 5);
    public static final b<String> aPo = d("vast_unsupported_video_extensions", "ogv,flv");
    public static final b<String> aPp = d("vast_unsupported_video_types", "video/ogg,video/x-flv");
    public static final b<Boolean> aPq = d("vast_validate_with_extension_if_no_video_type", true);
    public static final b<Integer> aPr = d("vast_video_selection_policy", Integer.valueOf(n.a.MEDIUM.ordinal()));
    public static final b<Integer> aPs = d("vast_wrapper_resolution_retry_count_v1", 1);
    public static final b<Integer> aPt = d("vast_wrapper_resolution_connection_timeout", Integer.valueOf((int) TimeUnit.SECONDS.toMillis(30)));
    public static final b<Integer> aPu = d("vast_industry_icon_max_size", 20);
    public static final b<Integer> aPv = d("vast_industry_icon_margin", 12);
    public static final b<Integer> aPw = d("vast_industry_icon_gravity", 85);
    public static final b<Integer> aPx = d("vast_native_mute_button_size", 24);
    public static final b<Integer> aPy = d("vast_native_play_pause_button_size", 24);
    public static final b<Integer> aPz = d("vast_native_video_widget_padding", 6);
    public static final b<Float> aPA = d("vast_native_video_widget_alpha", Float.valueOf(0.5f));
    public static final b<Boolean> aPB = d("vast_native_video_widgets_enabled", true);
    public static final b<Boolean> aPC = d("vast_replay_video_upon_completion", true);
    public static final b<Integer> aPD = d("vast_replay_icon_size", 64);
    public static final b<Boolean> aPE = d("vcjfhr", false);
    public static final b<String> aPF = d("vcjfhrr", "(?:<|%3C)script[^>]*src=\"(https[^\"]*\\.js[^\"]*)\".*?(?:>|%3E)");
    public static final b<Boolean> aPG = d("ree", true);
    public static final b<Integer> aPH = d("ree_t", Integer.valueOf(p.a.DEFAULT.getValue()));
    public static final b<Boolean> aPI = d("btee", true);
    public static final b<Integer> aPJ = d("btet", Integer.valueOf(p.a.DEFAULT.getValue()));
    public static final b<Boolean> aPK = d("reetoa", false);
    public static final b<Integer> aPL = d("reet_msfs", Integer.valueOf(p.a.DEFAULT.getValue()));
    public static final b<Integer> aPM = d("reet_msma", Integer.valueOf(p.a.V2.getValue()));
    public static final b<Integer> aPN = d("reet_msmd", Integer.valueOf(p.a.DEFAULT.getValue()));
    public static final b<Integer> aPO = d("reet_asfp", Integer.valueOf(p.a.DEFAULT.getValue()));
    public static final b<Integer> aPP = d("reet_asfg", Integer.valueOf(p.a.DEFAULT.getValue()));
    public static final b<Integer> aPQ = d("reet_aset", Integer.valueOf(p.a.DEFAULT.getValue()));
    public static final b<Integer> aPR = d("reet_esdi", Integer.valueOf(p.a.DEFAULT.getValue()));
    public static final b<Integer> aPS = d("reet_esrp", Integer.valueOf(p.a.DEFAULT.getValue()));
    public static final b<Boolean> aPT = d("apdra", false);
    public static final b<Boolean> aPU = d("apdrfs", false);
    public static final b<Boolean> aPV = d("apdrma", false);
    public static final b<Boolean> aPW = d("apdrmd", false);
    public static final b<Boolean> aPX = d("apdrfa", false);
    public static final b<Boolean> aPY = d("apdrev", false);
    public static final b<Boolean> aPZ = d("apdrdi", false);
    public static final b<Boolean> aQa = d("apdrrp", false);
    public static final b<Long> aQb = d("server_timestamp_ms", 0L);
    public static final b<Long> aQc = d("device_timestamp_ms", 0L);
    public static final b<Integer> aQd = d("gzip_min_length", 0);
    public static final b<Boolean> aQe = d("gzip_encoding_default", false);
    public static final b<Boolean> aQf = d("fetch_settings_gzip", false);
    public static final b<Boolean> aQg = d("device_init_gzip", false);
    public static final b<Boolean> aQh = d("fetch_ad_gzip", false);
    public static final b<Boolean> aQi = d("event_tracking_gzip", false);
    public static final b<Boolean> aQj = d("reward_postback_gzip", false);
    public static final b<Boolean> aQk = d("handle_render_process_gone", true);
    public static final b<Boolean> aQl = d("rworpg", true);
    public static final b<Boolean> aQm = d("fdadaomr", true);
    public static final b<Boolean> aQn = d("teorpc", false);
    public static final b<Boolean> aQo = d("set_webview_render_process_client", false);
    public static final b<Boolean> aQp = d("disable_webview_hardware_acceleration", false);
    public static final b<Boolean> aQq = d("anr_detection_enabled", false);
    public static final b<Long> aQr = d("anr_trigger_millis", 4000L);
    public static final b<Long> aQs = d("anr_touch_millis", 3000L);
    public static final b<Long> aQt = d("anr_check_millis", 3000L);
    public static final b<Boolean> aQu = d("uobid", true);
    public static final b<Boolean> aQv = d("bvde", false);
    public static final b<Long> aQw = d("bvdidm", 1000L);
    public static final b<Long> aQx = d("bvdim", 4000L);
    public static final b<Integer> aQy = d("bvdrs", 10);
    public static final b<Integer> aQz = d("bvdct", Integer.valueOf((int) InterfaceC13225hhc.td));
    public static final b<Boolean> aQA = d("bvad", false);
    public static final b<Boolean> aQB = d("bvebb", true);
    public static final b<Boolean> aQC = d("bvscb", true);
    public static final b<Boolean> aQD = d("apsobt", true);
    public static final b<Integer> aQE = d("tmtp", 1);
    public static final b<Integer> aQF = d("ntp", 5);
    public static final b<Boolean> aQG = d("uwtm", false);
    public static final b<Boolean> aQH = d("dwvvb", false);
    public static final b<Boolean> aQI = d("stcpc", true);
    public static final b<Boolean> aQJ = d("stcic", true);
    public static final b<Boolean> aQK = d("ueeem", false);
    public static final b<Boolean> aQL = d("upspfopsu", false);
    public static final b<Boolean> aQM = d("clacaf", false);
    public static final b<Boolean> aQN = d("qjscwwvl", false);
    public static final b<String> aQO = d("config_consent_dialog_state", "unknown");
    public static final b<String> aQP = d(com.anythink.expressad.foundation.g.a.bH, "");
    public static final b<String> aQQ = d("consent_flow_doc_url", "https://dash.applovin.com/documentation/mediation/android/getting-started/integration#enabling-max-built-in-consent-flow");
    public static final b<String> aQR = d("consent_flow_unity_doc_url", "https://dash.applovin.com/documentation/mediation/unity/getting-started/integration#max-built-in-consent-flow");
    public static final b<Integer> aQS = d("cfadtml", 20);
    public static final b<Boolean> aQT = d("ps_etr", false);
    public static final b<Long> aQU = d("ps_tri_ms", Long.valueOf(TimeUnit.DAYS.toMillis(7)));
    public static final b<Long> aQV = d("ps_ftri_ms", -1L);
    public static final b<Boolean> aQW = d("ps_sroftr", false);
    public static final b<Boolean> aQX = d("ps_sroftrof", false);
    public static final b<Boolean> aQY = d("communicator_enabled", true);
    public static final b<Boolean> aQZ = d("adse", true);

    public b(String str, T t) {
        if (str == null) {
            throw new IllegalArgumentException("No name specified");
        }
        if (t != null) {
            this.name = str;
            this.aKf = t;
            return;
        }
        throw new IllegalArgumentException("No default value specified");
    }

    public static Collection<b<?>> JC() {
        return Collections.synchronizedCollection(aKe.values());
    }

    public static <T> b<T> d(String str, T t) {
        if (t != null) {
            if (aKd.contains(t.getClass())) {
                b<T> bVar = new b<>(str, t);
                if (!aKe.containsKey(str)) {
                    aKe.put(str, bVar);
                    return bVar;
                }
                throw new IllegalArgumentException("Setting has already been used: " + str);
            }
            throw new IllegalArgumentException("Unsupported value type: " + t.getClass());
        }
        throw new IllegalArgumentException("No default value specified");
    }

    public T JB() {
        return this.aKf;
    }

    public T af(Object obj) {
        return (T) this.aKf.getClass().cast(obj);
    }

    @Override // java.lang.Comparable
    public int compareTo(Object obj) {
        if (obj instanceof b) {
            return this.name.compareTo(((b) obj).getName());
        }
        return 0;
    }

    public String getName() {
        return this.name;
    }
}
