package com.lenovo.anyshare;

import com.lenovo.anyshare.notification.media.local.data.PushType;

/* renamed from: com.lenovo.anyshare.eUa  reason: case insensitive filesystem */
/* loaded from: classes5.dex */
public final /* synthetic */ class C11211eUa {

    /* renamed from: a  reason: collision with root package name */
    public static final /* synthetic */ int[] f20302a = new int[PushType.values().length];
    public static final /* synthetic */ int[] b;

    static {
        f20302a[PushType.APP.ordinal()] = 1;
        f20302a[PushType.MUSIC.ordinal()] = 2;
        f20302a[PushType.SONG.ordinal()] = 3;
        f20302a[PushType.PLAYLIST.ordinal()] = 4;
        f20302a[PushType.HEADSET.ordinal()] = 5;
        f20302a[PushType.JUNK.ordinal()] = 6;
        f20302a[PushType.CLEAN.ordinal()] = 7;
        f20302a[PushType.STORAGE_FULL.ordinal()] = 8;
        f20302a[PushType.SCREEN_RECORDER.ordinal()] = 9;
        f20302a[PushType.CONNECT_TO_PC.ordinal()] = 10;
        f20302a[PushType.BIG_FILE.ordinal()] = 11;
        f20302a[PushType.BIG_VIDEO.ordinal()] = 12;
        f20302a[PushType.BIG_PHOTO.ordinal()] = 13;
        f20302a[PushType.BIG_AUDIO.ordinal()] = 14;
        f20302a[PushType.DUPLICATE_PHOTO.ordinal()] = 15;
        f20302a[PushType.DUPLICATE_VIDEO.ordinal()] = 16;
        f20302a[PushType.DUPLICATE_MUSIC.ordinal()] = 17;
        f20302a[PushType.SCREENSHOTS.ordinal()] = 18;
        f20302a[PushType.QL_JS.ordinal()] = 19;
        f20302a[PushType.QL_SD.ordinal()] = 20;
        f20302a[PushType.BD.ordinal()] = 21;
        f20302a[PushType.UNUSED_APP.ordinal()] = 22;
        f20302a[PushType.DOWNLOAD_VIDEO.ordinal()] = 23;
        f20302a[PushType.SEND_PHOTO.ordinal()] = 24;
        f20302a[PushType.PHOTO_MOMENT.ordinal()] = 25;
        f20302a[PushType.ACTIVE_ALBUM.ordinal()] = 26;
        f20302a[PushType.TOOLBOX_TAB.ordinal()] = 27;
        f20302a[PushType.TOOLBOX_ASTROLOGY.ordinal()] = 28;
        f20302a[PushType.TOOLBOX_IMG_TO_ZIP.ordinal()] = 29;
        f20302a[PushType.TOOLBOX_CHARACTER_AI.ordinal()] = 30;
        f20302a[PushType.TOOLBOX_MEME_CAM.ordinal()] = 31;
        f20302a[PushType.TOOLBOX_PROFILEPICTURE_AI.ordinal()] = 32;
        f20302a[PushType.TOOLBOX_LOTUS.ordinal()] = 33;
        f20302a[PushType.TOOLBOX_MERGE_PDF.ordinal()] = 34;
        f20302a[PushType.TOOLBOX_MYNOISE.ordinal()] = 35;
        f20302a[PushType.TOOLBOX_SAFEBOX.ordinal()] = 36;
        f20302a[PushType.TOOLBOX_VIDEO_TO_MP3.ordinal()] = 37;
        f20302a[PushType.TOOLBOX_PDF_TO_IMG.ordinal()] = 38;
        f20302a[PushType.TOOLBOX_IMG_COMPRESSOR.ordinal()] = 39;
        f20302a[PushType.TOOLBOX_VIDEO_COMPRESSOR.ordinal()] = 40;
        f20302a[PushType.TOOLBOX_PDF_COMPRESSOR.ordinal()] = 41;
        f20302a[PushType.TOOLBOX_SCRIBBLE_DIFFUSION.ordinal()] = 42;
        f20302a[PushType.TOOLBOX_ELON_MUSK.ordinal()] = 43;
        f20302a[PushType.TOOLBOX_SLEEP_TO_EARN.ordinal()] = 44;
        f20302a[PushType.TOOLBOX_QR_GENERATOR.ordinal()] = 45;
        f20302a[PushType.TOOLBOX_DAILY_HOROSCOPES.ordinal()] = 46;
        f20302a[PushType.TOOLBOX_GIFS_FINDER.ordinal()] = 47;
        f20302a[PushType.TOOLBOX_WHATSAPP_STICKER_MAKER.ordinal()] = 48;
        f20302a[PushType.TOOLBOX_SPLIT_PDF.ordinal()] = 49;
        f20302a[PushType.TOOLBOX_WORD_TO_PDF.ordinal()] = 50;
        f20302a[PushType.TOOLBOX_PDF_TO_WORD.ordinal()] = 51;
        f20302a[PushType.TOOLBOX_PDF_TO_POWERPOINT.ordinal()] = 52;
        f20302a[PushType.TOOLBOX_PDF_TO_EXCEL.ordinal()] = 53;
        f20302a[PushType.TOOLBOX_SCIENTIFIC_CALCULATOR.ordinal()] = 54;
        f20302a[PushType.TOOLBOX_DATE_CALCULATOR.ordinal()] = 55;
        f20302a[PushType.TOOLBOX_PREGNANCY_CALCULATOR.ordinal()] = 56;
        f20302a[PushType.TOOLBOX_BMI_CALCULATOR.ordinal()] = 57;
        f20302a[PushType.TOOLBOX_CURRENCY_CONVERTER.ordinal()] = 58;
        f20302a[PushType.WHATSAPP_STATUS.ordinal()] = 59;
        b = new int[PushType.values().length];
        b[PushType.APP.ordinal()] = 1;
        b[PushType.MUSIC.ordinal()] = 2;
        b[PushType.SONG.ordinal()] = 3;
        b[PushType.PLAYLIST.ordinal()] = 4;
        b[PushType.HEADSET.ordinal()] = 5;
        b[PushType.JUNK.ordinal()] = 6;
        b[PushType.CLEAN.ordinal()] = 7;
        b[PushType.STORAGE_FULL.ordinal()] = 8;
        b[PushType.SCREEN_RECORDER.ordinal()] = 9;
        b[PushType.CONNECT_TO_PC.ordinal()] = 10;
        b[PushType.BIG_FILE.ordinal()] = 11;
        b[PushType.DUPLICATE_PHOTO.ordinal()] = 12;
        b[PushType.DUPLICATE_VIDEO.ordinal()] = 13;
        b[PushType.SCREENSHOTS.ordinal()] = 14;
        b[PushType.DUPLICATE_MUSIC.ordinal()] = 15;
        b[PushType.QL_SD.ordinal()] = 16;
        b[PushType.QL_JS.ordinal()] = 17;
        b[PushType.CD.ordinal()] = 18;
        b[PushType.BIG_VIDEO.ordinal()] = 19;
        b[PushType.BIG_PHOTO.ordinal()] = 20;
        b[PushType.BIG_AUDIO.ordinal()] = 21;
        b[PushType.RESIDUAL.ordinal()] = 22;
        b[PushType.BD.ordinal()] = 23;
        b[PushType.UNUSED_APP.ordinal()] = 24;
        b[PushType.DOWNLOAD_VIDEO.ordinal()] = 25;
        b[PushType.SEND_PHOTO.ordinal()] = 26;
        b[PushType.PHOTO_MOMENT.ordinal()] = 27;
        b[PushType.ACTIVE_ALBUM.ordinal()] = 28;
        b[PushType.TOOLBOX_TAB.ordinal()] = 29;
        b[PushType.TOOLBOX_ASTROLOGY.ordinal()] = 30;
        b[PushType.TOOLBOX_IMG_TO_ZIP.ordinal()] = 31;
        b[PushType.TOOLBOX_CHARACTER_AI.ordinal()] = 32;
        b[PushType.TOOLBOX_MEME_CAM.ordinal()] = 33;
        b[PushType.TOOLBOX_PROFILEPICTURE_AI.ordinal()] = 34;
        b[PushType.TOOLBOX_LOTUS.ordinal()] = 35;
        b[PushType.TOOLBOX_MERGE_PDF.ordinal()] = 36;
        b[PushType.TOOLBOX_MYNOISE.ordinal()] = 37;
        b[PushType.TOOLBOX_SAFEBOX.ordinal()] = 38;
        b[PushType.TOOLBOX_VIDEO_TO_MP3.ordinal()] = 39;
        b[PushType.TOOLBOX_PDF_TO_IMG.ordinal()] = 40;
        b[PushType.TOOLBOX_IMG_COMPRESSOR.ordinal()] = 41;
        b[PushType.TOOLBOX_VIDEO_COMPRESSOR.ordinal()] = 42;
        b[PushType.TOOLBOX_PDF_COMPRESSOR.ordinal()] = 43;
        b[PushType.TOOLBOX_SCRIBBLE_DIFFUSION.ordinal()] = 44;
        b[PushType.TOOLBOX_ELON_MUSK.ordinal()] = 45;
        b[PushType.TOOLBOX_SLEEP_TO_EARN.ordinal()] = 46;
        b[PushType.TOOLBOX_QR_GENERATOR.ordinal()] = 47;
        b[PushType.TOOLBOX_DAILY_HOROSCOPES.ordinal()] = 48;
        b[PushType.TOOLBOX_GIFS_FINDER.ordinal()] = 49;
        b[PushType.TOOLBOX_WHATSAPP_STICKER_MAKER.ordinal()] = 50;
        b[PushType.TOOLBOX_SPLIT_PDF.ordinal()] = 51;
        b[PushType.TOOLBOX_WORD_TO_PDF.ordinal()] = 52;
        b[PushType.TOOLBOX_PDF_TO_WORD.ordinal()] = 53;
        b[PushType.TOOLBOX_PDF_TO_POWERPOINT.ordinal()] = 54;
        b[PushType.TOOLBOX_PDF_TO_EXCEL.ordinal()] = 55;
        b[PushType.TOOLBOX_SCIENTIFIC_CALCULATOR.ordinal()] = 56;
        b[PushType.TOOLBOX_DATE_CALCULATOR.ordinal()] = 57;
        b[PushType.TOOLBOX_PREGNANCY_CALCULATOR.ordinal()] = 58;
        b[PushType.TOOLBOX_BMI_CALCULATOR.ordinal()] = 59;
        b[PushType.TOOLBOX_CURRENCY_CONVERTER.ordinal()] = 60;
        b[PushType.WHATSAPP_STATUS.ordinal()] = 61;
    }
}
