package com.lenovo.anyshare;

import android.content.Context;
import android.content.res.Resources;
import android.view.View;
import android.view.ViewGroup;
import android.view.ViewStub;
import android.widget.FrameLayout;
import com.lenovo.anyshare.gps.R;
import com.lenovo.anyshare.widget.slidinguppanel.SlidingUpPanelLayout;
import com.ushareit.widget.tabhost.SITabHost;
import com.ushareit.widget.tabhost.SITabWidget;
import com.ytb.ui.MusicPlayerView;

/* renamed from: com.lenovo.anyshare.kee  reason: case insensitive filesystem */
/* loaded from: classes6.dex */
public class C15022kee implements InterfaceC13802iee {
    @Override // com.lenovo.anyshare.InterfaceC13802iee
    public View a(Context context, ViewGroup viewGroup, boolean z) throws Exception {
        Resources resources = context.getResources();
        FrameLayout frameLayout = new FrameLayout(context);
        ViewGroup.LayoutParams layoutParams = new FrameLayout.LayoutParams(-1, -1);
        frameLayout.setId(R.id.d6v);
        frameLayout.setClipChildren(false);
        frameLayout.setLayoutParams(layoutParams);
        if (viewGroup != null && z) {
            viewGroup.addView(frameLayout);
        }
        SlidingUpPanelLayout slidingUpPanelLayout = new SlidingUpPanelLayout(context);
        FrameLayout.LayoutParams layoutParams2 = new FrameLayout.LayoutParams(-1, -1);
        slidingUpPanelLayout.setId(R.id.dfx);
        slidingUpPanelLayout.setPanelHeight(context.getResources().getDimensionPixelSize(R.dimen.bs2));
        slidingUpPanelLayout.setDragView(R.id.cmq);
        slidingUpPanelLayout.setShadowHeight(0);
        slidingUpPanelLayout.setGravity(80);
        slidingUpPanelLayout.setPanelState(SlidingUpPanelLayout.PanelState.HIDDEN);
        slidingUpPanelLayout.setLayoutParams(layoutParams2);
        FrameLayout frameLayout2 = new FrameLayout(context);
        FrameLayout.LayoutParams layoutParams3 = new FrameLayout.LayoutParams(-1, -1);
        frameLayout2.setId(R.id.dlz);
        frameLayout2.setLayoutParams(layoutParams3);
        slidingUpPanelLayout.addView(frameLayout2);
        MusicPlayerView musicPlayerView = new MusicPlayerView(context);
        musicPlayerView.setId(R.id.cmq);
        musicPlayerView.setClickable(true);
        musicPlayerView.setFocusable(true);
        musicPlayerView.setLayoutParams(layoutParams3);
        slidingUpPanelLayout.addView(musicPlayerView);
        frameLayout.addView(slidingUpPanelLayout);
        ViewStub viewStub = new ViewStub(context);
        FrameLayout.LayoutParams layoutParams4 = new FrameLayout.LayoutParams(-1, -2);
        viewStub.setId(R.id.cq6);
        viewStub.setLayoutResource(R.layout.b3e);
        layoutParams4.gravity = 80;
        layoutParams4.bottomMargin = (int) resources.getDimension(R.dimen.bqz);
        viewStub.setLayoutParams(layoutParams4);
        frameLayout.addView(viewStub);
        ViewStub viewStub2 = new ViewStub(context);
        FrameLayout.LayoutParams layoutParams5 = new FrameLayout.LayoutParams(-1, -2);
        viewStub2.setId(R.id.bw4);
        viewStub2.setLayoutResource(R.layout.y5);
        layoutParams5.gravity = 80;
        layoutParams5.bottomMargin = (int) resources.getDimension(R.dimen.bqe);
        viewStub2.setLayoutParams(layoutParams5);
        frameLayout.addView(viewStub2);
        ViewStub viewStub3 = new ViewStub(context);
        FrameLayout.LayoutParams layoutParams6 = new FrameLayout.LayoutParams(-1, -2);
        viewStub3.setId(R.id.arr);
        viewStub3.setLayoutResource(R.layout.b6e);
        layoutParams6.gravity = 80;
        layoutParams6.bottomMargin = (int) resources.getDimension(R.dimen.bqe);
        viewStub3.setLayoutParams(layoutParams6);
        frameLayout.addView(viewStub3);
        ViewStub viewStub4 = new ViewStub(context);
        FrameLayout.LayoutParams layoutParams7 = new FrameLayout.LayoutParams(-1, -2);
        viewStub4.setId(R.id.apf);
        viewStub4.setLayoutResource(R.layout.tj);
        layoutParams7.gravity = 80;
        layoutParams7.bottomMargin = (int) resources.getDimension(R.dimen.bqe);
        viewStub4.setLayoutParams(layoutParams7);
        frameLayout.addView(viewStub4);
        SITabHost sITabHost = new SITabHost(context);
        FrameLayout.LayoutParams layoutParams8 = new FrameLayout.LayoutParams(-1, -2);
        sITabHost.setId(R.id.dm1);
        layoutParams8.gravity = 80;
        sITabHost.setClipChildren(false);
        sITabHost.setBackgroundResource(R.drawable.dnt);
        sITabHost.setLayoutParams(layoutParams8);
        frameLayout.addView(sITabHost);
        View view = new View(context);
        FrameLayout.LayoutParams layoutParams9 = new FrameLayout.LayoutParams(-1, 1);
        view.setId(R.id.bfo);
        layoutParams9.gravity = 48;
        view.setBackgroundColor(resources.getColor(R.color.bhj));
        view.setLayoutParams(layoutParams9);
        sITabHost.addView(view);
        SITabWidget sITabWidget = new SITabWidget(context);
        FrameLayout.LayoutParams layoutParams10 = new FrameLayout.LayoutParams(-1, (int) resources.getDimension(R.dimen.bqe));
        sITabWidget.setId(16908307);
        sITabWidget.setClipChildren(false);
        layoutParams10.leftMargin = context.getResources().getDimensionPixelOffset(R.dimen.bl2);
        layoutParams10.rightMargin = context.getResources().getDimensionPixelOffset(R.dimen.bl2);
        sITabWidget.setBackgroundColor(resources.getColor(R.color.bi0));
        sITabWidget.setOrientation(0);
        sITabWidget.setLayoutParams(layoutParams10);
        sITabHost.addView(sITabWidget);
        FrameLayout frameLayout3 = new FrameLayout(context);
        FrameLayout.LayoutParams layoutParams11 = new FrameLayout.LayoutParams(0, 0);
        frameLayout3.setId(16908305);
        frameLayout3.setLayoutParams(layoutParams11);
        sITabHost.addView(frameLayout3);
        FrameLayout frameLayout4 = new FrameLayout(context);
        FrameLayout.LayoutParams layoutParams12 = new FrameLayout.LayoutParams(-1, -2);
        frameLayout4.setId(R.id.top);
        frameLayout4.setClickable(true);
        layoutParams12.gravity = 48;
        frameLayout4.setLayoutParams(layoutParams12);
        frameLayout.addView(frameLayout4);
        FrameLayout frameLayout5 = new FrameLayout(context);
        FrameLayout.LayoutParams layoutParams13 = new FrameLayout.LayoutParams(-1, -1);
        frameLayout5.setId(R.id.bzj);
        frameLayout5.setClickable(true);
        frameLayout5.setVisibility(8);
        frameLayout5.setLayoutParams(layoutParams13);
        frameLayout.addView(frameLayout5);
        FrameLayout frameLayout6 = new FrameLayout(context);
        FrameLayout.LayoutParams layoutParams14 = new FrameLayout.LayoutParams(-1, -1);
        frameLayout6.setId(R.id.e33);
        frameLayout6.setClickable(true);
        frameLayout6.setVisibility(8);
        frameLayout6.setLayoutParams(layoutParams14);
        frameLayout.addView(frameLayout6);
        ViewStub viewStub5 = new ViewStub(context);
        FrameLayout.LayoutParams layoutParams15 = new FrameLayout.LayoutParams(-1, -1);
        viewStub5.setId(R.id.dja);
        viewStub5.setInflatedId(R.id.be3);
        viewStub5.setLayoutResource(R.layout.aka);
        viewStub5.setLayoutParams(layoutParams15);
        frameLayout.addView(viewStub5);
        ViewStub viewStub6 = new ViewStub(context);
        FrameLayout.LayoutParams layoutParams16 = new FrameLayout.LayoutParams(-1, -1);
        viewStub6.setId(R.id.cy0);
        viewStub6.setLayoutResource(R.layout.b6k);
        layoutParams16.gravity = 80;
        viewStub6.setLayoutParams(layoutParams16);
        frameLayout.addView(viewStub6);
        ViewStub viewStub7 = new ViewStub(context);
        FrameLayout.LayoutParams layoutParams17 = new FrameLayout.LayoutParams(-1, -2);
        viewStub7.setId(R.id.cxy);
        viewStub7.setLayoutResource(R.layout.b6h);
        layoutParams17.bottomMargin = (int) resources.getDimension(R.dimen.bqz);
        layoutParams17.gravity = 80;
        viewStub7.setLayoutParams(layoutParams17);
        frameLayout.addView(viewStub7);
        ViewStub viewStub8 = new ViewStub(context);
        FrameLayout.LayoutParams layoutParams18 = new FrameLayout.LayoutParams(-1, -1);
        viewStub8.setId(R.id.cy1);
        viewStub8.setLayoutResource(R.layout.b6l);
        layoutParams18.gravity = 80;
        viewStub8.setLayoutParams(layoutParams18);
        frameLayout.addView(viewStub8);
        ViewStub viewStub9 = new ViewStub(context);
        FrameLayout.LayoutParams layoutParams19 = new FrameLayout.LayoutParams(-2, -2);
        viewStub9.setId(R.id.cxz);
        viewStub9.setLayoutResource(R.layout.b6i);
        layoutParams19.bottomMargin = (int) resources.getDimension(R.dimen.br3);
        layoutParams19.gravity = 85;
        viewStub9.setLayoutParams(layoutParams19);
        frameLayout.addView(viewStub9);
        FrameLayout frameLayout7 = new FrameLayout(context);
        FrameLayout.LayoutParams layoutParams20 = new FrameLayout.LayoutParams(resources.getDimensionPixelOffset(R.dimen.bru), resources.getDimensionPixelOffset(R.dimen.bru));
        frameLayout7.setId(R.id.bpc);
        layoutParams20.gravity = 48;
        layoutParams20.topMargin = (int) resources.getDimension(R.dimen.bks);
        frameLayout7.setLayoutParams(layoutParams20);
        frameLayout.addView(frameLayout7);
        FrameLayout frameLayout8 = new FrameLayout(context);
        FrameLayout.LayoutParams layoutParams21 = new FrameLayout.LayoutParams(resources.getDimensionPixelOffset(R.dimen.bru), resources.getDimensionPixelOffset(R.dimen.bru));
        frameLayout8.setId(R.id.bpe);
        layoutParams21.gravity = 85;
        layoutParams21.bottomMargin = (int) resources.getDimension(R.dimen.bks);
        frameLayout8.setLayoutParams(layoutParams21);
        frameLayout.addView(frameLayout8);
        View view2 = new View(context);
        ViewGroup.LayoutParams layoutParams22 = new ViewGroup.LayoutParams(-1, -1);
        view2.setId(R.id.drw);
        view2.setClickable(true);
        view2.setVisibility(8);
        view2.setLayoutParams(layoutParams22);
        frameLayout.addView(view2);
        return frameLayout;
    }
}
