package com.lenovo.anyshare;

import com.anythink.basead.ui.GuideToClickView;
import com.anythink.expressad.foundation.h.p;
import com.bytedance.sdk.openadsdk.TTAdConstant;
import com.lenovo.anyshare.bizentertainment.incentive.widget.CoinCircleProgressView;
import com.unity3d.services.banners.UnityBannerSize;
import com.ushareit.feed.holder.WallpaperItemHolder;
import com.ushareit.muslim.prayers.alarm.toolbar.ToolbarService;
import com.vungle.warren.utility.ViewUtility;
import java.util.HashMap;
import java.util.Map;
import org.threeten.bp.chrono.HijrahDate;

/* renamed from: com.lenovo.anyshare.nic  reason: case insensitive filesystem */
/* loaded from: classes5.dex */
public final class C16896nic {
    public static final short A = 191;
    public static final short Aa = 327;
    public static final short Ab = 451;
    public static final short Ac = 583;
    public static final short Ad = 772;
    public static final short Ae = 953;
    public static final short B = 192;
    public static final short Ba = 328;
    public static final short Bb = 452;
    public static final short Bc = 584;
    public static final short Bd = 773;
    public static final short Be = 954;
    public static final short C = 193;
    public static final short Ca = 329;
    public static final short Cb = 453;
    public static final short Cc = 585;
    public static final short Cd = 774;
    public static final short Ce = 955;
    public static final short D = 194;
    public static final short Da = 330;
    public static final short Db = 454;
    public static final short Dc = 586;
    public static final short Dd = 826;
    public static final short De = 956;
    public static final short E = 195;
    public static final short Ea = 331;
    public static final short Eb = 455;
    public static final short Ec = 587;
    public static final short Ed = 827;
    public static final short Ee = 957;
    public static final short F = 196;
    public static final short Fa = 332;
    public static final short Fb = 456;
    public static final short Fc = 639;
    public static final short Fd = 828;
    public static final short Fe = 958;
    public static final short G = 197;
    public static final short Ga = 333;
    public static final short Gb = 457;
    public static final short Gc = 640;
    public static final short Gd = 830;
    public static final short Ge = 959;
    public static final short H = 240;
    public static final short Ha = 334;
    public static final short Hb = 458;
    public static final short Hc = 661;
    public static final short Hd = 831;
    public static final Map<Short, C18726qic> He = a();
    public static final short I = 241;
    public static final short Ia = 335;
    public static final short Ib = 459;
    public static final short Ic = 662;
    public static final short Id = 832;
    public static final short J = 242;
    public static final short Ja = 336;
    public static final short Jb = 460;
    public static final short Jc = 663;
    public static final short Jd = 833;
    public static final short K = 243;
    public static final short Ka = 378;
    public static final short Kb = 461;
    public static final short Kc = 664;
    public static final short Kd = 834;
    public static final short L = 244;
    public static final short La = 379;
    public static final short Lb = 462;
    public static final short Lc = 665;
    public static final short Ld = 835;
    public static final short M = 245;
    public static final short Ma = 380;
    public static final short Mb = 463;
    public static final short Mc = 666;
    public static final short Md = 836;
    public static final short N = 246;
    public static final short Na = 381;
    public static final short Nb = 464;
    public static final short Nc = 667;
    public static final short Nd = 837;
    public static final short O = 247;
    public static final short Oa = 382;
    public static final short Ob = 465;
    public static final short Oc = 648;
    public static final short Od = 889;
    public static final short P = 248;
    public static final short Pa = 383;
    public static final short Pb = 466;
    public static final short Pc = 700;
    public static final short Pd = 890;
    public static final short Q = 249;
    public static final short Qa = 384;
    public static final short Qb = 467;
    public static final short Qc = 701;
    public static final short Qd = 891;
    public static final short R = 250;
    public static final short Ra = 385;
    public static final short Rb = 468;
    public static final short Rc = 702;
    public static final short Rd = 892;
    public static final short S = 251;
    public static final short Sa = 386;
    public static final short Sb = 469;
    public static final short Sc = 703;
    public static final short Sd = 893;
    public static final short T = 252;
    public static final short Ta = 387;
    public static final short Tb = 470;
    public static final short Tc = 704;
    public static final short Td = 894;
    public static final short U = 253;
    public static final short Ua = 388;
    public static final short Ub = 471;
    public static final short Uc = 705;
    public static final short Ud = 895;
    public static final short V = 254;
    public static final short Va = 389;
    public static final short Vb = 507;
    public static final short Vc = 706;
    public static final short Vd = 896;
    public static final short W = 255;
    public static final short Wa = 390;
    public static final short Wb = 508;
    public static final short Wc = 707;
    public static final short Wd = 897;
    public static final short X = 256;
    public static final short Xa = 391;
    public static final short Xb = 509;
    public static final short Xc = 708;
    public static final short Xd = 898;
    public static final short Y = 257;
    public static final short Ya = 392;
    public static final short Yb = 510;
    public static final short Yc = 709;
    public static final short Yd = 899;
    public static final short Z = 258;
    public static final short Za = 393;
    public static final short Zb = 511;
    public static final short Zc = 710;
    public static final short Zd = 900;
    public static final short _a = 394;
    public static final short _b = 512;
    public static final short _c = 711;
    public static final short _d = 901;

    /* renamed from: a  reason: collision with root package name */
    public static final short f24448a = 4;
    public static final short aa = 259;
    public static final short ab = 395;
    public static final short ac = 513;
    public static final short ad = 712;
    public static final short ae = 902;
    public static final short b = 119;
    public static final short ba = 260;
    public static final short bb = 396;
    public static final short bc = 514;
    public static final short bd = 713;
    public static final short be = 903;
    public static final short c = 120;
    public static final short ca = 261;
    public static final short cb = 397;
    public static final short cc = 515;
    public static final short cd = 714;
    public static final short ce = 904;
    public static final short d = 121;
    public static final short da = 262;
    public static final short db = 398;
    public static final short dc = 516;
    public static final short dd = 715;
    public static final short de = 906;
    public static final short e = 122;
    public static final short ea = 263;
    public static final short eb = 399;
    public static final short ec = 517;
    public static final short ed = 716;
    public static final short ee = 909;
    public static final short f = 123;
    public static final short fa = 264;
    public static final short fb = 400;
    public static final short fc = 518;
    public static final short fd = 717;
    public static final short fe = 910;
    public static final short g = 124;
    public static final short ga = 265;
    public static final short gb = 401;
    public static final short gc = 519;
    public static final short gd = 718;
    public static final short ge = 911;
    public static final short h = 125;
    public static final short ha = 266;
    public static final short hb = 402;
    public static final short hc = 520;
    public static final short hd = 719;
    public static final short he = 912;
    public static final short i = 126;
    public static final short ia = 267;
    public static final short ib = 403;
    public static final short ic = 521;
    public static final short id = 720;
    public static final short ie = 913;
    public static final short j = 127;
    public static final short ja = 268;
    public static final short jb = 404;
    public static final short jc = 522;
    public static final short jd = 721;
    public static final short je = 914;
    public static final short k = 128;
    public static final short ka = 269;
    public static final short kb = 405;
    public static final short kc = 523;
    public static final short kd = 722;
    public static final short ke = 915;
    public static final short l = 129;
    public static final short la = 270;
    public static final short lb = 406;
    public static final short lc = 524;
    public static final short ld = 723;
    public static final short le = 916;
    public static final short m = 130;
    public static final short ma = 271;
    public static final short mb = 407;
    public static final short mc = 525;
    public static final short md = 724;

    /* renamed from: me  reason: collision with root package name */
    public static final short f24449me = 917;
    public static final short n = 131;
    public static final short na = 272;
    public static final short nb = 408;
    public static final short nc = 526;
    public static final short nd = 725;
    public static final short ne = 918;
    public static final short o = 132;
    public static final short oa = 273;
    public static final short ob = 409;
    public static final short oc = 527;
    public static final short od = 726;
    public static final short oe = 919;
    public static final short p = 133;
    public static final short pa = 316;
    public static final short pb = 410;
    public static final short pc = 528;
    public static final short pd = 727;
    public static final short pe = 920;
    public static final short q = 134;
    public static final short qa = 317;
    public static final short qb = 411;
    public static final short qc = 529;
    public static final short qd = 728;
    public static final short qe = 923;
    public static final short r = 135;
    public static final short ra = 318;
    public static final short rb = 412;
    public static final short rc = 574;
    public static final short rd = 729;
    public static final short re = 924;
    public static final short s = 136;
    public static final short sa = 319;
    public static final short sb = 443;
    public static final short sc = 575;
    public static final short sd = 730;
    public static final short se = 925;
    public static final short t = 137;
    public static final short ta = 320;
    public static final short tb = 444;
    public static final short tc = 576;
    public static final short td = 763;
    public static final short te = 926;
    public static final short u = 138;
    public static final short ua = 321;
    public static final short ub = 445;
    public static final short uc = 577;
    public static final short ud = 764;
    public static final short ue = 927;
    public static final short v = 139;
    public static final short va = 322;
    public static final short vb = 446;
    public static final short vc = 578;
    public static final short vd = 765;
    public static final short ve = 928;
    public static final short w = 187;
    public static final short wa = 323;
    public static final short wb = 447;
    public static final short wc = 579;
    public static final short wd = 766;
    public static final short we = 933;
    public static final short x = 188;
    public static final short xa = 324;
    public static final short xb = 448;
    public static final short xc = 580;
    public static final short xd = 767;
    public static final short xe = 937;
    public static final short y = 189;
    public static final short ya = 325;
    public static final short yb = 449;
    public static final short yc = 581;
    public static final short yd = 769;
    public static final short ye = 938;
    public static final short z = 190;
    public static final short za = 326;
    public static final short zb = 450;
    public static final short zc = 582;
    public static final short zd = 771;
    public static final short ze = 959;

    public static Map<Short, C18726qic> a() {
        HashMap hashMap = new HashMap();
        a(hashMap, 4, "transform.rotation");
        a(hashMap, 119, "protection.lockrotation");
        a(hashMap, 120, "protection.lockaspectratio");
        a(hashMap, 121, "protection.lockposition");
        a(hashMap, 122, "protection.lockagainstselect");
        a(hashMap, 123, "protection.lockcropping");
        a(hashMap, 124, "protection.lockvertices");
        a(hashMap, 125, "protection.locktext");
        a(hashMap, 126, "protection.lockadjusthandles");
        a(hashMap, 127, "protection.lockagainstgrouping", (byte) 1);
        a(hashMap, 128, "text.textid");
        a(hashMap, 129, "text.textleft");
        a(hashMap, 130, "text.texttop");
        a(hashMap, 131, "text.textright");
        a(hashMap, 132, "text.textbottom");
        a(hashMap, 133, "text.wraptext");
        a(hashMap, 134, "text.scaletext");
        a(hashMap, 135, "text.anchortext");
        a(hashMap, 136, "text.textflow");
        a(hashMap, 137, "text.fontrotation");
        a(hashMap, 138, "text.idofnextshape");
        a(hashMap, 139, "text.bidir");
        a(hashMap, 187, "text.singleclickselects");
        a(hashMap, InterfaceC13225hhc.Ec, "text.usehostmargins");
        a(hashMap, InterfaceC13225hhc.Fc, "text.rotatetextwithshape");
        a(hashMap, InterfaceC13225hhc.Gc, "text.sizeshapetofittext");
        a(hashMap, InterfaceC13225hhc.Hc, "text.sizetexttofitshape", (byte) 1);
        a(hashMap, InterfaceC13225hhc.Ic, "geotext.unicode");
        a(hashMap, InterfaceC13225hhc.Jc, "geotext.rtftext");
        a(hashMap, InterfaceC13225hhc.Kc, "geotext.alignmentoncurve");
        a(hashMap, InterfaceC13225hhc.Lc, "geotext.defaultpointsize");
        a(hashMap, InterfaceC13225hhc.Mc, "geotext.textspacing");
        a(hashMap, InterfaceC13225hhc.Nc, "geotext.fontfamilyname");
        a(hashMap, 240, "geotext.reverseroworder");
        a(hashMap, InterfaceC13225hhc.Ed, "geotext.hastexteffect");
        a(hashMap, InterfaceC13225hhc.Fd, "geotext.rotatecharacters");
        a(hashMap, InterfaceC13225hhc.Gd, "geotext.kerncharacters");
        a(hashMap, InterfaceC13225hhc.Hd, "geotext.tightortrack");
        a(hashMap, InterfaceC13225hhc.Id, "geotext.stretchtofitshape");
        a(hashMap, InterfaceC13225hhc.Jd, "geotext.charboundingbox");
        a(hashMap, InterfaceC13225hhc.Kd, "geotext.scaletextonpath");
        a(hashMap, InterfaceC13225hhc.Ld, "geotext.stretchcharheight");
        a(hashMap, InterfaceC13225hhc.Md, "geotext.nomeasurealongpath");
        a(hashMap, 250, "geotext.boldfont");
        a(hashMap, 251, "geotext.italicfont");
        a(hashMap, 252, "geotext.underlinefont");
        a(hashMap, 253, "geotext.shadowfont");
        a(hashMap, 254, "geotext.smallcapsfont");
        a(hashMap, 255, "geotext.strikethroughfont");
        a(hashMap, 256, "blip.cropfromtop");
        a(hashMap, 257, "blip.cropfrombottom");
        a(hashMap, 258, "blip.cropfromleft");
        a(hashMap, 259, "blip.cropfromright");
        a(hashMap, C5415Qbi.d, "blip.bliptodisplay");
        a(hashMap, C5415Qbi.e, "blip.blipfilename");
        a(hashMap, 262, "blip.blipflags");
        a(hashMap, 263, "blip.transparentcolor");
        a(hashMap, 264, "blip.contrastsetting");
        a(hashMap, 265, "blip.brightnesssetting");
        a(hashMap, 266, "blip.gamma");
        a(hashMap, 267, "blip.pictureid");
        a(hashMap, 268, "blip.doublemod");
        a(hashMap, 269, "blip.picturefillmod");
        a(hashMap, CoinCircleProgressView.f19061a, "blip.pictureline");
        a(hashMap, 271, "blip.printblip");
        a(hashMap, ToolbarService.b, "blip.printblipfilename");
        a(hashMap, 273, "blip.printflags");
        a(hashMap, 316, "blip.nohittestpicture");
        a(hashMap, 317, "blip.picturegray");
        a(hashMap, 318, "blip.picturebilevel");
        a(hashMap, 319, "blip.pictureactive");
        a(hashMap, 320, "geometry.left");
        a(hashMap, WallpaperItemHolder.f31505a, "geometry.top");
        a(hashMap, 322, "geometry.right");
        a(hashMap, 323, "geometry.bottom");
        a(hashMap, 324, "geometry.shapepath", (byte) 3);
        a(hashMap, 325, "geometry.vertices", (byte) 5);
        a(hashMap, 326, "geometry.segmentinfo", (byte) 5);
        a(hashMap, 327, "geometry.adjustvalue");
        a(hashMap, 328, "geometry.adjust2value");
        a(hashMap, 329, "geometry.adjust3value");
        a(hashMap, ViewUtility.INPUT_DPI, "geometry.adjust4value");
        a(hashMap, 331, "geometry.adjust5value");
        a(hashMap, 332, "geometry.adjust6value");
        a(hashMap, 333, "geometry.adjust7value");
        a(hashMap, HijrahDate.MAX_ADJUSTED_CYCLE, "geometry.adjust8value");
        a(hashMap, 335, "geometry.adjust9value");
        a(hashMap, 336, "geometry.adjust10value");
        a(hashMap, 378, "geometry.shadowOK");
        a(hashMap, 379, "geometry.3dok");
        a(hashMap, 380, "geometry.lineok");
        a(hashMap, 381, "geometry.geotextok");
        a(hashMap, 382, "geometry.fillshadeshapeok");
        a(hashMap, 383, "geometry.fillok", (byte) 1);
        a(hashMap, 384, "fill.filltype");
        a(hashMap, 385, "fill.fillcolor", (byte) 2);
        a(hashMap, 386, "fill.fillopacity");
        a(hashMap, 387, "fill.fillbackcolor", (byte) 2);
        a(hashMap, 388, "fill.backopacity");
        a(hashMap, 389, "fill.crmod");
        a(hashMap, 390, "fill.patterntexture");
        a(hashMap, 391, "fill.blipfilename");
        a(hashMap, 392, "fill.blipflags");
        a(hashMap, 393, "fill.width");
        a(hashMap, 394, "fill.height");
        a(hashMap, 395, "fill.angle");
        a(hashMap, 396, "fill.focus");
        a(hashMap, 397, "fill.toleft");
        a(hashMap, 398, "fill.totop");
        a(hashMap, 399, "fill.toright");
        a(hashMap, 400, "fill.tobottom");
        a(hashMap, TTAdConstant.MATE_IS_NULL_CODE, "fill.rectleft");
        a(hashMap, TTAdConstant.AD_ID_IS_NULL_CODE, "fill.recttop");
        a(hashMap, TTAdConstant.DEEPLINK_UNAVAILABLE_CODE, "fill.rectright");
        a(hashMap, 404, "fill.rectbottom");
        a(hashMap, TTAdConstant.DEEPLINK_FALLBACK_TYPE_CODE, "fill.dztype");
        a(hashMap, TTAdConstant.LANDING_PAGE_TYPE_CODE, "fill.shadepreset");
        a(hashMap, TTAdConstant.DOWNLOAD_APP_INFO_CODE, "fill.shadecolors", (byte) 5);
        a(hashMap, TTAdConstant.DOWNLOAD_URL_CODE, "fill.originx");
        a(hashMap, TTAdConstant.IMAGE_LIST_CODE, "fill.originy");
        a(hashMap, TTAdConstant.IMAGE_LIST_SIZE_CODE, "fill.shapeoriginx");
        a(hashMap, TTAdConstant.IMAGE_CODE, "fill.shapeoriginy");
        a(hashMap, TTAdConstant.IMAGE_URL_CODE, "fill.shadetype");
        a(hashMap, 443, "fill.filled");
        a(hashMap, 444, "fill.hittestfill");
        a(hashMap, 445, "fill.shape");
        a(hashMap, 446, "fill.userect");
        a(hashMap, 447, "fill.nofillhittest", (byte) 1);
        a(hashMap, p.a.f2823a, "linestyle.color", (byte) 2);
        a(hashMap, 449, "linestyle.opacity");
        a(hashMap, 450, "linestyle.backcolor", (byte) 2);
        a(hashMap, 451, "linestyle.crmod");
        a(hashMap, 452, "linestyle.linetype");
        a(hashMap, 453, "linestyle.fillblip");
        a(hashMap, 454, "linestyle.fillblipname");
        a(hashMap, 455, "linestyle.fillblipflags");
        a(hashMap, 456, "linestyle.fillwidth");
        a(hashMap, 457, "linestyle.fillheight");
        a(hashMap, 458, "linestyle.filldztype");
        a(hashMap, 459, "linestyle.linewidth");
        a(hashMap, 460, "linestyle.linemiterlimit");
        a(hashMap, 461, "linestyle.linestyle");
        a(hashMap, 462, "linestyle.linedashing");
        a(hashMap, 463, "linestyle.linedashstyle", (byte) 5);
        a(hashMap, 464, "linestyle.linestartarrowhead");
        a(hashMap, 465, "linestyle.lineendarrowhead");
        a(hashMap, 466, "linestyle.linestartarrowwidth");
        a(hashMap, 467, "linestyle.lineestartarrowlength");
        a(hashMap, UnityBannerSize.BannerSize.IAB_STANDARD_WIDTH, "linestyle.lineendarrowwidth");
        a(hashMap, 469, "linestyle.lineendarrowlength");
        a(hashMap, 470, "linestyle.linejoinstyle");
        a(hashMap, 471, "linestyle.lineendcapstyle");
        a(hashMap, GuideToClickView.a.g, "linestyle.arrowheadsok");
        a(hashMap, 508, "linestyle.anyline");
        a(hashMap, 509, "linestyle.hitlinetest");
        a(hashMap, 510, "linestyle.linefillshape");
        a(hashMap, 511, "linestyle.nolinedrawdash", (byte) 1);
        a(hashMap, 512, "shadowstyle.type");
        a(hashMap, 513, "shadowstyle.color", (byte) 2);
        a(hashMap, 514, "shadowstyle.highlight");
        a(hashMap, 515, "shadowstyle.crmod");
        a(hashMap, 516, "shadowstyle.opacity");
        a(hashMap, 517, "shadowstyle.offsetx");
        a(hashMap, 518, "shadowstyle.offsety");
        a(hashMap, 519, "shadowstyle.secondoffsetx");
        a(hashMap, 520, "shadowstyle.secondoffsety");
        a(hashMap, 521, "shadowstyle.scalextox");
        a(hashMap, 522, "shadowstyle.scaleytox");
        a(hashMap, 523, "shadowstyle.scalextoy");
        a(hashMap, 524, "shadowstyle.scaleytoy");
        a(hashMap, 525, "shadowstyle.perspectivex");
        a(hashMap, 526, "shadowstyle.perspectivey");
        a(hashMap, 527, "shadowstyle.weight");
        a(hashMap, 528, "shadowstyle.originx");
        a(hashMap, 529, "shadowstyle.originy");
        a(hashMap, 574, "shadowstyle.shadow");
        a(hashMap, 575, "shadowstyle.shadowobsured");
        a(hashMap, C4042Lhc.f, "perspective.type");
        a(hashMap, 577, "perspective.offsetx");
        a(hashMap, 578, "perspective.offsety");
        a(hashMap, 579, "perspective.scalextox");
        a(hashMap, 580, "perspective.scaleytox");
        a(hashMap, 581, "perspective.scalextoy");
        a(hashMap, 582, "perspective.scaleytoy");
        a(hashMap, 583, "perspective.perspectivex");
        a(hashMap, 584, "perspective.perspectivey");
        a(hashMap, 585, "perspective.weight");
        a(hashMap, 586, "perspective.originx");
        a(hashMap, 587, "perspective.originy");
        a(hashMap, 639, "perspective.perspectiveon");
        a(hashMap, 640, "3d.specularamount");
        a(hashMap, 661, "3d.diffuseamount");
        a(hashMap, 662, "3d.shininess");
        a(hashMap, 663, "3d.edgethickness");
        a(hashMap, 664, "3d.extrudeforward");
        a(hashMap, 665, "3d.extrudebackward");
        a(hashMap, TTAdConstant.STYLE_SIZE_RADIO_2_3, "3d.extrudeplane");
        a(hashMap, 667, "3d.extrusioncolor", (byte) 2);
        a(hashMap, 648, "3d.crmod");
        a(hashMap, 700, "3d.3deffect");
        a(hashMap, 701, "3d.metallic");
        a(hashMap, 702, "3d.useextrusioncolor", (byte) 2);
        a(hashMap, 703, "3d.lightface");
        a(hashMap, 704, "3dstyle.yrotationangle");
        a(hashMap, 705, "3dstyle.xrotationangle");
        a(hashMap, 706, "3dstyle.rotationaxisx");
        a(hashMap, 707, "3dstyle.rotationaxisy");
        a(hashMap, 708, "3dstyle.rotationaxisz");
        a(hashMap, 709, "3dstyle.rotationangle");
        a(hashMap, 710, "3dstyle.rotationcenterx");
        a(hashMap, 711, "3dstyle.rotationcentery");
        a(hashMap, 712, "3dstyle.rotationcenterz");
        a(hashMap, 713, "3dstyle.rendermode");
        a(hashMap, 714, "3dstyle.tolerance");
        a(hashMap, 715, "3dstyle.xviewpoint");
        a(hashMap, 716, "3dstyle.yviewpoint");
        a(hashMap, 717, "3dstyle.zviewpoint");
        a(hashMap, 718, "3dstyle.originx");
        a(hashMap, 719, "3dstyle.originy");
        a(hashMap, 720, "3dstyle.skewangle");
        a(hashMap, 721, "3dstyle.skewamount");
        a(hashMap, 722, "3dstyle.ambientintensity");
        a(hashMap, 723, "3dstyle.keyx");
        a(hashMap, 724, "3dstyle.keyy");
        a(hashMap, 725, "3dstyle.keyz");
        a(hashMap, 726, "3dstyle.keyintensity");
        a(hashMap, 727, "3dstyle.fillx");
        a(hashMap, UnityBannerSize.BannerSize.LEADERBOARD_WIDTH, "3dstyle.filly");
        a(hashMap, 729, "3dstyle.fillz");
        a(hashMap, 730, "3dstyle.fillintensity");
        a(hashMap, 763, "3dstyle.constrainrotation");
        a(hashMap, 764, "3dstyle.rotationcenterauto");
        a(hashMap, 765, "3dstyle.parallel");
        a(hashMap, 766, "3dstyle.keyharsh");
        a(hashMap, 767, "3dstyle.fillharsh");
        a(hashMap, 769, "shape.master");
        a(hashMap, 771, "shape.connectorstyle");
        a(hashMap, 772, "shape.blackandwhitesettings");
        a(hashMap, 773, "shape.wmodepurebw");
        a(hashMap, 774, "shape.wmodebw");
        a(hashMap, 826, "shape.oleicon");
        a(hashMap, 827, "shape.preferrelativeresize");
        a(hashMap, 828, "shape.lockshapetype");
        a(hashMap, 830, "shape.deleteattachedobject");
        a(hashMap, 831, "shape.backgroundshape");
        a(hashMap, 832, "callout.callouttype");
        a(hashMap, 833, "callout.xycalloutgap");
        a(hashMap, 834, "callout.calloutangle");
        a(hashMap, 835, "callout.calloutdroptype");
        a(hashMap, 836, "callout.calloutdropspecified");
        a(hashMap, 837, "callout.calloutlengthspecified");
        a(hashMap, 889, "callout.iscallout");
        a(hashMap, 890, "callout.calloutaccentbar");
        a(hashMap, 891, "callout.callouttextborder");
        a(hashMap, 892, "callout.calloutminusx");
        a(hashMap, 893, "callout.calloutminusy");
        a(hashMap, 894, "callout.dropauto");
        a(hashMap, 895, "callout.lengthspecified");
        a(hashMap, 896, "groupshape.shapename");
        a(hashMap, 897, "groupshape.description");
        a(hashMap, 898, "groupshape.hyperlink");
        a(hashMap, 899, "groupshape.wrappolygonvertices", (byte) 5);
        a(hashMap, 900, "groupshape.wrapdistleft");
        a(hashMap, 901, "groupshape.wrapdisttop");
        a(hashMap, 902, "groupshape.wrapdistright");
        a(hashMap, 903, "groupshape.wrapdistbottom");
        a(hashMap, com.anythink.expressad.video.dynview.a.a.t, "groupshape.regroupid");
        a(hashMap, 906, "unused906");
        a(hashMap, 909, "groupshape.wzTooltip");
        a(hashMap, 910, "groupshape.wzScript");
        a(hashMap, 911, "groupshape.posh");
        a(hashMap, 912, "groupshape.posrelh");
        a(hashMap, 913, "groupshape.posv");
        a(hashMap, 914, "groupshape.posrelv");
        a(hashMap, 915, "groupshape.pctHR");
        a(hashMap, 916, "groupshape.alignHR");
        a(hashMap, 917, "groupshape.dxHeightHR");
        a(hashMap, 918, "groupshape.dxWidthHR");
        a(hashMap, 919, "groupshape.wzScriptExtAttr");
        a(hashMap, 920, "groupshape.scriptLang");
        a(hashMap, 923, "groupshape.borderTopColor");
        a(hashMap, 924, "groupshape.borderLeftColor");
        a(hashMap, 925, "groupshape.borderBottomColor");
        a(hashMap, 926, "groupshape.borderRightColor");
        a(hashMap, 927, "groupshape.tableProperties");
        a(hashMap, 928, "groupshape.tableRowProperties");
        a(hashMap, 933, "groupshape.wzWebBot");
        a(hashMap, 937, "groupshape.metroBlob");
        a(hashMap, 938, "groupshape.dhgt");
        a(hashMap, 959, "groupshape.GroupShapeBooleanProperties");
        a(hashMap, 953, "groupshape.editedwrap");
        a(hashMap, 954, "groupshape.behinddocument");
        a(hashMap, 955, "groupshape.ondblclicknotify");
        a(hashMap, 956, "groupshape.isbutton");
        a(hashMap, 957, "groupshape.1dadjustment");
        a(hashMap, 958, "groupshape.hidden");
        a(hashMap, 959, "groupshape.print", (byte) 1);
        return hashMap;
    }

    public static byte b(short s2) {
        C18726qic c18726qic = He.get(Short.valueOf(s2));
        if (c18726qic == null) {
            return (byte) 0;
        }
        return c18726qic.h;
    }

    public static void a(Map<Short, C18726qic> map, int i2, String str) {
        map.put(Short.valueOf((short) i2), new C18726qic(str));
    }

    public static void a(Map<Short, C18726qic> map, int i2, String str, byte b2) {
        map.put(Short.valueOf((short) i2), new C18726qic(str, b2));
    }

    public static String a(short s2) {
        C18726qic c18726qic = He.get(Short.valueOf(s2));
        return c18726qic == null ? "unknown" : c18726qic.g;
    }
}
