package com.lenovo.anyshare;

/* renamed from: com.lenovo.anyshare.aNf  reason: case insensitive filesystem */
/* loaded from: classes7.dex */
public class C8701aNf {

    /* renamed from: a  reason: collision with root package name */
    public static String f18408a = "{\n                    \"cat_id\": \"11\",\n                    \"category\": \"Top Sites\",\n                    \"code\": \"whatsapp\",\n                    \"desc\": \"Popular Message App \",\n                    \"icon\": \"\",\n                    \"imp_url\": \"\",\n                    \"is_new\": \"0\",\n                    \"jump_warn\": 0,\n                    \"like_num\": \"800472k\",\n                    \"name\": \"WhatsApp\",\n                    \"restricted\": \"0\",\n                    \"status\": \"2\",\n                    \"tag\": \"\",\n                    \"tag_show\": \"1\",\n                    \"url2\": \"com.whatsapp\"\n                }";
    public static String b = "{\"data\":[{\"category\":\"Top Sites\",\"code\":\"top_sites\",\"icon\":\"\",\"id\":\"11\",\"sites\":[{\"cat_id\":\"11\",\"category\":\"Top Sites\",\"code\":\"instagram\",\"desc\":\"\",\"icon\":\"\",\"imp_url\":\"\",\"is_new\":\"1\",\"jump_warn\":0,\"like_num\":\"0k\",\"name\":\"Instagram\",\"restricted\":\"0\",\"status\":\"2\",\"tag\":\"\",\"tag_show\":\"0\",\"url2\":\"https://www.instagram.com/\"},{\"cat_id\":\"11\",\"category\":\"Top Sites\",\"code\":\"facebook\",\"desc\":\"\",\"icon\":\"\",\"imp_url\":\"\",\"is_new\":\"1\",\"jump_warn\":0,\"like_num\":\"0k\",\"name\":\"Facebook\",\"restricted\":\"0\",\"status\":\"2\",\"tag\":\"\",\"tag_show\":\"0\",\"url2\":\"https://m.facebook.com/\"},{\"cat_id\":\"11\",\"category\":\"Top Sites\",\"code\":\"twitter\",\"desc\":\"\",\"icon\":\"\",\"imp_url\":\"\",\"is_new\":\"1\",\"jump_warn\":0,\"like_num\":\"0k\",\"name\":\"Twitter\",\"restricted\":\"0\",\"status\":\"2\",\"tag\":\"\",\"tag_show\":\"0\",\"url2\":\"https://m.twitter.com/\"},{\"cat_id\":\"11\",\"category\":\"Top Sites\",\"code\":\"facebook watch\",\"desc\":\"\",\"icon\":\"\",\"imp_url\":\"\",\"is_new\":\"1\",\"jump_warn\":0,\"like_num\":\"0k\",\"name\":\"FB Watch\",\"restricted\":\"0\",\"status\":\"2\",\"tag\":\"\",\"tag_show\":\"0\",\"url2\":\"https://m.facebook.com/watch/\"},{\"cat_id\":\"11\",\"category\":\"Top Sites\",\"code\":\"vimeo\",\"desc\":\"Video-sharing site. Users can upload &amp; share videos.\",\"icon\":\"\",\"imp_url\":\"\",\"is_new\":\"0\",\"jump_warn\":0,\"like_num\":\"389842k\",\"name\":\"Vimeo\",\"restricted\":\"0\",\"status\":\"2\",\"tag\":\"\",\"tag_show\":\"1\",\"url2\":\"https://vimeo.com/\"},{\"cat_id\":\"11\",\"category\":\"Top Sites\",\"code\":\"dailymotion\",\"desc\":\"\",\"icon\":\"\",\"imp_url\":\"\",\"is_new\":\"1\",\"jump_warn\":0,\"like_num\":\"0k\",\"name\":\"Dailymotion\",\"restricted\":\"0\",\"status\":\"2\",\"tag\":\"\",\"tag_show\":\"0\",\"url2\":\"http://www.dailymotion.com/in\"},{\"cat_id\":\"11\",\"category\":\"Top Sites\",\"code\":\"ted\",\"desc\":\"\",\"icon\":\"\",\"imp_url\":\"\",\"is_new\":\"1\",\"jump_warn\":0,\"like_num\":\"0k\",\"name\":\"TED\",\"restricted\":\"0\",\"status\":\"2\",\"tag\":\"\",\"tag_show\":\"0\",\"url2\":\"https://www.ted.com/\"}]}],\"lastupdatetime\":\"74229dc3464187cb6e71d6264a4b985f\",\"status\":1,\"total\":72}";
    public static String c = "eyJkYXRhIjpbeyJjYXRlZ29yeSI6IlRvcCBTaXRlcyIsImNvZGUiOiJ0b3Bfc2l0ZXMiLCJpY29u\nIjoiIiwiaWQiOiIxMSIsInNpdGVzIjpbeyJjYXRfaWQiOiIxMSIsImNhdGVnb3J5IjoiVG9wIFNp\ndGVzIiwiY29kZSI6Imluc3RhZ3JhbSIsImRlc2MiOiIiLCJpY29uIjoiIiwiaW1wX3VybCI6IiIs\nImlzX25ldyI6IjEiLCJqdW1wX3dhcm4iOjAsImxpa2VfbnVtIjoiMGsiLCJuYW1lIjoiSW5zdGFn\ncmFtIiwicmVzdHJpY3RlZCI6IjAiLCJzdGF0dXMiOiIyIiwidGFnIjoiIiwidGFnX3Nob3ciOiIw\nIiwidXJsMiI6Imh0dHBzOi8vd3d3Lmluc3RhZ3JhbS5jb20vIn0seyJjYXRfaWQiOiIxMSIsImNh\ndGVnb3J5IjoiVG9wIFNpdGVzIiwiY29kZSI6IllvdVR1YmUiLCJkZXNjIjoiIiwiaWNvbiI6IiIs\nImltcF91cmwiOiIiLCJpc19uZXciOiIxIiwianVtcF93YXJuIjowLCJsaWtlX251bSI6IjBrIiwi\nbmFtZSI6IllvdVR1YmUiLCJyZXN0cmljdGVkIjoiMCIsInN0YXR1cyI6IjIiLCJ0YWciOiIiLCJ0\nYWdfc2hvdyI6IjAiLCJ1cmwyIjoiaHR0cHM6Ly9tLnlvdXR1YmUuY29tLyJ9LHsiY2F0X2lkIjoi\nMTEiLCJjYXRlZ29yeSI6IlRvcCBTaXRlcyIsImNvZGUiOiJmYWNlYm9vayIsImRlc2MiOiIiLCJp\nY29uIjoiIiwiaW1wX3VybCI6IiIsImlzX25ldyI6IjEiLCJqdW1wX3dhcm4iOjAsImxpa2VfbnVt\nIjoiMGsiLCJuYW1lIjoiRmFjZWJvb2siLCJyZXN0cmljdGVkIjoiMCIsInN0YXR1cyI6IjIiLCJ0\nYWciOiIiLCJ0YWdfc2hvdyI6IjAiLCJ1cmwyIjoiaHR0cHM6Ly9tLmZhY2Vib29rLmNvbS8ifSx7\nImNhdF9pZCI6IjExIiwiY2F0ZWdvcnkiOiJUb3AgU2l0ZXMiLCJjb2RlIjoiZmFjZWJvb2sgd2F0\nY2giLCJkZXNjIjoiIiwiaWNvbiI6IiIsImltcF91cmwiOiIiLCJpc19uZXciOiIxIiwianVtcF93\nYXJuIjowLCJsaWtlX251bSI6IjBrIiwibmFtZSI6IkZCIFdhdGNoIiwicmVzdHJpY3RlZCI6IjAi\nLCJzdGF0dXMiOiIyIiwidGFnIjoiIiwidGFnX3Nob3ciOiIwIiwidXJsMiI6Imh0dHBzOi8vbS5m\nYWNlYm9vay5jb20vd2F0Y2gvIn0seyJjYXRfaWQiOiIxMSIsImNhdGVnb3J5IjoiVG9wIFNpdGVz\nIiwiY29kZSI6InZpbWVvIiwiZGVzYyI6IlZpZGVvLXNoYXJpbmcgc2l0ZS4gVXNlcnMgY2FuIHVw\nbG9hZCAmYW1wOyBzaGFyZSB2aWRlb3MuIiwiaWNvbiI6IiIsImltcF91cmwiOiIiLCJpc19uZXci\nOiIwIiwianVtcF93YXJuIjowLCJsaWtlX251bSI6IjM4OTg0MmsiLCJuYW1lIjoiVmltZW8iLCJy\nZXN0cmljdGVkIjoiMCIsInN0YXR1cyI6IjIiLCJ0YWciOiIiLCJ0YWdfc2hvdyI6IjEiLCJ1cmwy\nIjoiaHR0cHM6Ly92aW1lby5jb20vIn0seyJjYXRfaWQiOiIxMSIsImNhdGVnb3J5IjoiVG9wIFNp\ndGVzIiwiY29kZSI6ImRhaWx5bW90aW9uIiwiZGVzYyI6IiIsImljb24iOiIiLCJpbXBfdXJsIjoi\nIiwiaXNfbmV3IjoiMSIsImp1bXBfd2FybiI6MCwibGlrZV9udW0iOiIwayIsIm5hbWUiOiJEYWls\neW1vdGlvbiIsInJlc3RyaWN0ZWQiOiIwIiwic3RhdHVzIjoiMiIsInRhZyI6IiIsInRhZ19zaG93\nIjoiMCIsInVybDIiOiJodHRwOi8vd3d3LmRhaWx5bW90aW9uLmNvbS9pbiJ9LHsiY2F0X2lkIjoi\nMTEiLCJjYXRlZ29yeSI6IlRvcCBTaXRlcyIsImNvZGUiOiJ0ZWQiLCJkZXNjIjoiIiwiaWNvbiI6\nIiIsImltcF91cmwiOiIiLCJpc19uZXciOiIxIiwianVtcF93YXJuIjowLCJsaWtlX251bSI6IjBr\nIiwibmFtZSI6IlRFRCIsInJlc3RyaWN0ZWQiOiIwIiwic3RhdHVzIjoiMiIsInRhZyI6IiIsInRh\nZ19zaG93IjoiMCIsInVybDIiOiJodHRwczovL3d3dy50ZWQuY29tLyJ9XX1dLCJsYXN0dXBkYXRl\ndGltZSI6Ijc0MjI5ZGMzNDY0MTg3Y2I2ZTcxZDYyNjRhNGI5ODVmIiwic3RhdHVzIjoxLCJ0b3Rh\nbCI6NzJ9\n";
    public static String d;

    static {
        d = DCf.c() ? DCf.a(c) : b;
    }
}
