package com.lenovo.anyshare;

import com.ushareit.base.core.net.Ping;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/* renamed from: com.lenovo.anyshare.aPi  reason: case insensitive filesystem */
/* loaded from: classes8.dex */
public class C8726aPi {
    public int A;
    public long B;
    public long Ba;
    public String C;
    public String Ca;
    public String D;
    public String E;
    public String F;
    public long G;
    public String H;
    public int Ha;
    public String I;
    public boolean J;
    public String K;
    public int L;
    public boolean M;
    public String N;
    public String O;
    public int P;
    public boolean Q;
    public String Qa;
    public String R;
    public ArrayList<Map<String, Object>> Ra;
    public boolean S;
    public C11241eWi Sa;
    public boolean T;
    public boolean U;
    public String Ua;
    public String Wa;
    public String Xa;
    public String Ya;
    public ZOi Za;

    /* renamed from: a  reason: collision with root package name */
    public String f18423a;
    public String ab;
    public String b;
    public String bb;
    public String c;
    public int cb;
    public String d;
    public String da;
    public String e;
    public String eb;
    public String f;
    public String g;
    public String ga;
    public String h;
    public String i;
    public String ia;
    public String j;
    public String ja;
    public String k;
    public String ka;
    public String l;
    public String la;
    public String m;
    public int ma;
    public String n;
    public String na;
    public String o;
    public String oa;
    public String p;
    public String q;
    public String r;
    public String ra;
    public String s;
    public String t;
    public String u;
    public List<String> v;
    public String va;
    public String w;
    public String x;
    public String xa;
    public long y;
    public String z;
    public boolean V = true;
    public boolean W = false;
    public boolean X = false;
    public boolean Y = false;
    public boolean Z = false;
    public boolean aa = false;
    public boolean ba = false;
    public boolean ca = false;
    public String ea = null;
    public String fa = null;
    public boolean ha = false;
    public long pa = -1;
    public long qa = -1;
    public long sa = -1;
    public long ta = 0;
    public long ua = -1;
    public long wa = -1;
    public long ya = -1;
    public long za = -1;
    public long Aa = -1;
    public long Da = -1;
    public long Ea = -1;
    public long Fa = -1;
    public long Ga = -1;
    public long Ia = -1;
    public long Ja = -1;
    public long Ka = -1;
    public long La = -1;
    public long Ma = -1;
    public long Na = -1;
    public Ping.a Oa = null;
    public int Pa = 0;
    public long Ta = 0;
    public String Va = null;
    public long _a = -1;
    public List<Long> db = new ArrayList();
}
