package com.lenovo.anyshare;

import android.os.Parcel;
import com.anythink.core.api.ATAdConst;
import com.google.android.gms.ads.RequestConfiguration;
import kotlin.NotImplementedError;

@Rek(bv = {1, 0, 3}, d1 = {"\u0000,\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0000\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0011\n\u0000\n\u0002\u0010\b\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0002\b\u0003\bf\u0018\u0000*\u0004\b\u0000\u0010\u00012\u00020\u0002J\u0015\u0010\u0003\u001a\u00028\u00002\u0006\u0010\u0004\u001a\u00020\u0005H&¢\u0006\u0002\u0010\u0006J\u001b\u0010\u0007\u001a\b\u0012\u0004\u0012\u00028\u00000\b2\u0006\u0010\t\u001a\u00020\nH\u0016¢\u0006\u0002\u0010\u000bJ!\u0010\f\u001a\u00020\r*\u00028\u00002\u0006\u0010\u0004\u001a\u00020\u00052\u0006\u0010\u000e\u001a\u00020\nH&¢\u0006\u0002\u0010\u000f¨\u0006\u0010"}, d2 = {"Lkotlinx/parcelize/Parceler;", RequestConfiguration.MAX_AD_CONTENT_RATING_T, "", "create", "parcel", "Landroid/os/Parcel;", "(Landroid/os/Parcel;)Ljava/lang/Object;", "newArray", "", ATAdConst.NETWORK_REQUEST_PARAMS_KEY.BANNER_SIZE, "", "(I)[Ljava/lang/Object;", "write", "", "flags", "(Ljava/lang/Object;Landroid/os/Parcel;I)V", "parcelize-runtime"}, k = 1, mv = {1, 4, 0})
/* renamed from: com.lenovo.anyshare.yrk  reason: case insensitive filesystem */
/* loaded from: classes9.dex */
public interface InterfaceC23727yrk<T> {

    /* renamed from: com.lenovo.anyshare.yrk$a */
    /* loaded from: classes9.dex */
    public static final class a {
        public static <T> T[] a(InterfaceC23727yrk<T> interfaceC23727yrk, int i) {
            throw new NotImplementedError("Generated by Android Extensions automatically");
        }
    }

    T a(Parcel parcel);

    void a(T t, Parcel parcel, int i);

    T[] newArray(int i);
}
