package com.lenovo.anyshare;

import com.lenovo.anyshare.gps.R;
import com.ushareit.base.core.utils.lang.ObjectStore;

/* loaded from: classes8.dex */
public class LEi {

    /* renamed from: a  reason: collision with root package name */
    public static final String f11295a = a(R.string.aoz);
    public static final String b = a(R.string.ape);
    public static final String c = a(R.string.apz);
    public static final String d = a(R.string.api);
    public static final String e = a(R.string.aq1);
    public static final String f = a(R.string.apu);
    public static final String g = a(R.string.apb);
    public static final String h = a(R.string.ap4);
    public static final String i = a(R.string.ap7);
    public static final String j = a(R.string.aq4);
    public static final String k = a(R.string.ap_);
    public static final String l = a(R.string.ap2);
    public static final String m = a(R.string.aq0);
    public static final String n = a(R.string.apq);
    public static final String o = a(R.string.ap1);
    public static final String p = a(R.string.apf);
    public static final String q = a(R.string.apk);
    public static final String r = a(R.string.aq3);
    public static final String s = a(R.string.apw);
    public static final String t = a(R.string.ap5);
    public static final String u = a(R.string.ap9);
    public static final String v = a(R.string.apd);
    public static final String w = a(R.string.apa);
    public static final String x = a(R.string.aoy);
    public static final String y = a(R.string.aph);
    public static final String z = a(R.string.apv);
    public static final String A = a(R.string.aq2);
    public static final String B = a(R.string.apj);
    public static final String C = a(R.string.ap8);
    public static final String D = a(R.string.ap0);
    public static final String E = a(R.string.apl);
    public static final String F = a(R.string.apo);
    public static final String G = a(R.string.apn);
    public static final String H = a(R.string.app);
    public static final String I = a(R.string.apm);
    public static final String J = a(R.string.apx);
    public static final String K = a(R.string.apc);
    public static final String L = a(R.string.apr);
    public static final String M = a(R.string.ap6);
    public static final String N = a(R.string.ap3);
    public static final String O = a(R.string.apy);
    public static final String P = a(R.string.as_);
    public static final String Q = a(R.string.ar5);
    public static final String R = a(R.string.ar6);
    public static final String S = a(R.string.ark);
    public static final String T = a(R.string.arl);
    public static final String U = a(R.string.arm);
    public static final String V = a(R.string.arn);
    public static final String W = a(R.string.ard);
    public static final String X = a(R.string.as0);
    public static final String Y = a(R.string.as1);
    public static final String Z = a(R.string.as2);
    public static final String aa = a(R.string.as3);
    public static final String ba = a(R.string.at4);
    public static final String ca = a(R.string.at5);
    public static final String da = a(R.string.asc);
    public static final String ea = a(R.string.asd);
    public static final String fa = a(R.string.asn);
    public static final String ga = a(R.string.aso);
    public static final String ha = a(R.string.asf);
    public static final String ia = a(R.string.asg);
    public static final String ja = a(R.string.asv);
    public static final String ka = a(R.string.asw);
    public static final String la = a(R.string.asa);
    public static final String ma = a(R.string.asb);
    public static final String na = a(R.string.aru);
    public static final String oa = a(R.string.arv);
    public static final String pa = a(R.string.ary);
    public static final String qa = a(R.string.arz);
    public static final String ra = a(R.string.arw);
    public static final String sa = a(R.string.arx);
    public static final String ta = a(R.string.asp);
    public static final String ua = a(R.string.asq);
    public static final String va = a(R.string.as6);
    public static final String wa = a(R.string.as7);
    public static final String xa = a(R.string.as8);
    public static final String ya = a(R.string.as9);
    public static final String za = a(R.string.ar9);
    public static final String Aa = a(R.string.ar_);
    public static final String Ba = a(R.string.ast);
    public static final String Ca = a(R.string.asu);
    public static final String Da = a(R.string.ar4);
    public static final String Ea = a(R.string.asx);
    public static final String Fa = a(R.string.asy);
    public static final String Ga = a(R.string.ash);
    public static final String Ha = a(R.string.asi);
    public static final String Ia = a(R.string.at1);
    public static final String Ja = a(R.string.at2);
    public static final String Ka = a(R.string.ara);
    public static final String La = a(R.string.arb);
    public static final String Ma = a(R.string.asz);
    public static final String Na = a(R.string.at0);
    public static final String Oa = a(R.string.are);
    public static final String Pa = a(R.string.arf);
    public static final String Qa = a(R.string.ar7);
    public static final String Ra = a(R.string.ar8);
    public static final String Sa = a(R.string.arj);
    public static final String Ta = a(R.string.asr);
    public static final String Ua = a(R.string.ass);
    public static final String Va = a(R.string.as5);
    public static final String Wa = a(R.string.ari);
    public static final String Xa = a(R.string.art);
    public static final String Ya = a(R.string.aro);
    public static final String Za = a(R.string.arp);
    public static final String _a = a(R.string.att);

    public static final String a(int i2) {
        return ObjectStore.getContext().getString(i2);
    }
}
